apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:spqTsrf+4oMxn+AJ9wedhvty0uq9GYqKgK+W8ujVmf2TdEZgSkMyUZSIAe6qJaa9mwVE0+YNEGuRy2yK1gPm0y9cZ7l7TMOsIRaepdTPnA==,iv:Rmd5YajNYmnLNvhbroQP0tMol0JlHIIMz5B1wHCzlIY=,tag:13BOOUbJ5+5HnpMt4a1M4g==,type:comment]
    webhook_url: ENC[AES256_GCM,data:NdyieQHLDpsDvJeFwUFni49ln1UxUBXFZlDeVtk+pKvoVRydjxcqF2LS/RJPp5ddRhrx/Xvt7MNDLM8L5946KqhdBm6K81LZ4pE2lp4CHMS6KwCz9Kqkn1xFo8vfqSqmL9Rzw3NOK8QV8FDJdvtnMHG93c54uH+uGGzXljL6sA==,iv:jMhWTcKaUNqe+zOQXtvTNqQJRbk9yiNvA+ZDadxlcUI=,tag:YVlVPpg5gOQDyGKdljTgmg==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dHpKSG51Mnd2Y3hPbG4v
            azVteDh3RWR6RkpOWjhUTGtmcUVCbDhjaGxrCkcvcEZNV3hia0RRb2J4dVkwYUJM
            UnlWVzk5UHdZWHp1R2txNkg2WmpVdzAKLS0tIGk5dTRyT1dMTFNCbnJvY0I5YUhy
            VXVBWlg0R1ZjNC9wOXZCTldXZEhtNU0K4dhajbmHC6qv67pjtrmKA5ZVtfpSZfuE
            Q/FyDvwAzx7ndtdSb+Bh5bveP+1HebynEpsw6yiZh2CYJw3767ot+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T01:07:08Z"
    mac: ENC[AES256_GCM,data:aBqE3V6H/HLy1pqgNqlKXO8p4ja3qmYNj8NS9Inqza32z6vrR9EFzllndwHYQbr9/SvCHkVNHhJwOn0z7dQaamqhSnHYW4dZ7Zws8XMBgxK0N8E8Knq/q3OlejQ6ZoEKsiYOlAcYjD4geWEFmDpCIP215y0fAngWSN5VVSuKDak=,iv:kMt/3iFXFhHBU8oiGlBKKFYn4KvftbXhWx3bskcDGZY=,tag:NFZS2RJwuDvFMlISCTpqtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
