apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
  namespace: observability
type: Opaque
stringData:
  #ENC[AES256_GCM,data:spqTsrf+4oMxn+AJ9wedhvty0uq9GYqKgK+W8ujVmf2TdEZgSkMyUZSIAe6qJaa9mwVE0+YNEGuRy2yK1gPm0y9cZ7l7TMOsIRaepdTPnA==,iv:Rmd5YajNYmnLNvhbroQP0tMol0JlHIIMz5B1wHCzlIY=,tag:13BOOUbJ5+5HnpMt4a1M4g==,type:comment]
  webhook_url: ""
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dHpKSG51Mnd2Y3hPbG4v
        azVteDh3RWR6RkpOWjhUTGtmcUVCbDhjaGxrCkcvcEZNV3hia0RRb2J4dVkwYUJM
        UnlWVzk5UHdZWHp1R2txNkg2WmpVdzAKLS0tIGk5dTRyT1dMTFNCbnJvY0I5YUhy
        VXVBWlg0R1ZjNC9wOXZCTldXZEhtNU0K4dhajbmHC6qv67pjtrmKA5ZVtfpSZfuE
        Q/FyDvwAzx7ndtdSb+Bh5bveP+1HebynEpsw6yiZh2CYJw3767ot+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T05:23:33Z"
  mac: ENC[AES256_GCM,data:GnA7/KiI43T+v9yKkIL8p7efGQaBpNfpwm38mMU22kOuS106lIQNfOAI/ZOZyPHviUPfUq7tPG8PYftK0jN0yZuEv5J3ut9iw+fzs6nRIxFLq+6NnNMWnGOCIveHIaigoi2LCmalHpBW/nj56+bXeqDjqTp2pF2dP2ND7fMGXqQ=,iv:/u4E20OiujAEdE24jb2naEPC8hcUYU3ouLZD3RCH21o=,tag:0fiRhJoV6xhamEnzdObhqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
