# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./httproute-prometheus.yaml
  - ./httproute-alertmanager.yaml
  - ./alertmanager-discord.sops.yaml
  - ./prometheusrule-observability-stack.yaml
  - ./rules/prometheusrule-synthetic-k6-canaries.yaml
  - ./prometheusrule-apps.yaml
  - ./prometheusrule-app-traffic.yaml
  - ./prometheusrule-platform-flux.yaml
  - ./prometheusrule-platform-cert-manager.yaml
  - ./prometheusrule-platform-longhorn.yaml
  - ./prometheusrule-platform-cilium.yaml
  - ./prometheusrule-platform-envoy-gateway.yaml
  - ./prometheusrule-platform-renovate-operator.yaml
