# TEMPLATE: encrypt to secret.sops.yaml with SOPS (do not commit plaintext secrets)
#
# Example:
#   sops --encrypt --in-place kubernetes/apps/observability/twitch-exporter/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: twitch-exporter-secret
  namespace: observability
type: Opaque
stringData:
  TWITCH_CLIENT_ID: ENC[AES256_GCM,data:dtBDZvL10iDIQyvoZk502m0Dn5hzlOiUEqRZ+gtP,iv:teNfEhGB2I8W4O7DyuJokoFvEBH1R2QIRBTjGtcKsXw=,tag:6/58U2pLxVAcncxOxL8OZg==,type:str]
  TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:Srg8oswbYtrFfxdpeEdOnlnHUeUzt6Ee5QttZYWW,iv:bKp7uji10CoyhYTzN+ItGBHjSDFfpwrxcrl5uailKko=,tag:tMqoXGVDK710G47dvBAthw==,type:str]
  TWITCH_SELF_CHANNEL: ENC[AES256_GCM,data:0f8XgmumLA==,iv:qblxY3qDweiCaP4jZfb3j522sFSi9Agl0pd6JqIppN8=,tag:yhrghaPTvCUQAdO/sr7kYQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRHE3cWxGWFpZSnVLUzNx
        TjR0UzlCMnlHeGwzTXNoWjVnQlZibElGUzNrClFtOHoyZWxhblRmUk9qRTZUeU5B
        N2RGdjhYSTRSazVneE5PcXJLT0V2azAKLS0tIDA5aDkrRmdiVnl0aGJFTUtUMWt3
        RW5WYWpKcHNWcExleXJBRXU1M2VkVm8KRutIcWGcIn2mbtXuOiWG+oD2tFnQHyie
        ZmPG4j7/o2mKi7AEJpH6G8DKxVTUI82rR4yYGGnK4tfZDdIiO9sXFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T18:34:52Z"
  mac: ENC[AES256_GCM,data:oNGLN/yEMIivKGqQCY39ymwMdj+5GuDYVIc74SgaP5wqOpydDGTj5PLptL/LQVMSuSRHqN7KPZSos4JV04sZDNb2uSuCqI/pbkHEF7Z+FazEbW9dV3/21sUizWmNppi/wQaFJDwMYLilunygxHKWVniALdNZxhYsf5D1iA9+RTU=,iv:HAsM4/G01jUQM/OlhVExY+ylxG0IEWPBBfbxQRBBvYM=,tag:pfWaSXv53b4uvxBKSSy/5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
