---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-unseal
  namespace: vault-unseal
spec:
  interval: 1h
  path: ./kubernetes/apps/vault-unseal/vault-unseal/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: vault-unseal
  timeout: 10m
  wait: true
