---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  chart:
    spec:
      chart: charts/gitops-server
      version: 0.38.0
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
  interval: 1h
  values:
    adminUser:
      create: true
      createSecret: false
      username: ${GITOPS_UI_ADMIN_USERNAME:=wego-admin}
    rbac:
      impersonationResourceNames:
        - ${GITOPS_UI_ADMIN_USERNAME:=wego-admin}
    envVars:
      - name: WEAVE_GITOPS_FEATURE_TENANCY
        value: "true"
      - name: WEAVE_GITOPS_FEATURE_CLUSTER
        value: "false"
      - name: WEAVE_GITOPS_FEATURE_GITOPS_RUNTIME
        value: "false"
    service:
      annotations: {}
      type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
