apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
stringData:
  username: ENC[AES256_GCM,data:c46405v0+eDOnQ==,iv:3OKxrFIBftqqOJnYWi3W6Hb04N56XluEmLHN/wm6kCE=,tag:x/+TojAh35itq6tSN/ruBg==,type:str]
  password: ENC[AES256_GCM,data:dhMTfbwdyzg0q/txJL9LBiXEa7qvswuw3+T4aPmKDH+3NSuBQVfRl2+RkaeJGmrWl64kogos5OIXpRwv,iv:DRRoWF3QdGchU9A+jaivSMH4tL1g+Fjd4l3DMvPBlYw=,tag:ghPCLdc/xO10eEufhpg10w==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaVF2c2RrZTl2RXFFTWZo
        QWRNeG9zRlVpT3plU1NSMHdwR0doY0VDd0VVClhpeDVYdGNoOFN6Zk1zRElaV1pB
        bjZaV01xUHcrZGdXdDd4OWZmUERyTlUKLS0tIDBlU2NTY2JHbjE0cUhmaHppN1Nr
        S2JZZEZxY1hocnQ2MmpIS1gxTkhKc3cKkcEeGjPreytF3kHFogpzF3MJ1alkwtAs
        MhPrJuhdw0Syyvt7yVHZgTLvL9QVdoOGEzk2Lfvc145t9c6O2D4zxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T11:52:43Z"
  mac: ENC[AES256_GCM,data:rCL+02n2UnqdgAy5yctb8m1QyscbQ8ARiRDZktgQERw9A892uqrrgga/lLAgT+kCRjCdJAY2IBVEix79C+8B9p3U5vbGPg0yBs0hyyRkKhtNlKSzzzWzjpX+fm578n1Z+feptQIkRdv7163ztUfekKkqlZZzW+VCQcnfXPwPqJo=,iv:Tf8z5OyEN98DNG60WRDiP8ahetCNaErLzwkfeZ5l7iw=,tag:vK37xPhgUL4tlh4lBw5BwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
