---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oncall
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  hostnames:
    - oncall.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: oncall-engine
          namespace: observability
          port: 8080
