apiVersion: v1
kind: ConfigMap
metadata:
  name: sparkyfitness-frontend-config
  namespace: sparkyfitness
data:
  TZ: ${TIMEZONE}
  # Used by the frontend container's internal nginx proxy
  SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server
  SPARKY_FITNESS_SERVER_PORT: "3010"
