apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-secret
    namespace: sparkyfitness
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:waTDa3tD,iv:Rqriz4py7CvZb4wFjY27sI8lsF1VmDmKfjaj5sM7mDc=,tag:Z10a6pDmS36ozq+6HruCZg==,type:str]
    password: ENC[AES256_GCM,data:MWF2INH3MagIsZq8WWNoTBhBZOOr5el8SCjlZj27gZLXTTkS6JHYwpBWEJAwka6VbY4HqOPTpZLS/KFuE/CO4Q==,iv:1lGumRXznOjloYpDOP3aHA5E0oXSEFUECHMddycMRP0=,tag:f6LTLT1EDYvKfX+EczNLbA==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM3NkeC9yalIzUGZYamxV
            THVEQjQ3UGVLL095aTk1Z08vY2lJV1JyelRJCmZvZVZJMldHaGdBZ3RFYVFWcXJZ
            NWEyWGl2dUFzdWcwOS82V2xLeWRNU3MKLS0tIFByVWZIenpMcGpHTGxRTXIrVXh5
            WEVyZ1VySDJOYjhYT2VjOUczem9US0kKT1Yi/pNnEGiSqhhg15T3N1U/kGX3cUFx
            50X7KOtUQTsq/Iw/WCPAQtqHn+wby81JzLs4qjfEDorH1Edm0/Hjxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T04:05:27Z"
    mac: ENC[AES256_GCM,data:HTIhaUO0sZlW7dMCubizAJmIMMmsNzYDmr5OGUuZXz8Fv7UN4sIJTTOlRHy6dJHbZtUqnn/kuLSnyYZKX9KkOlPzHVOlu3y8REX6HuKdJqvG7sJsjxzYwPFajDDEK0iYA8JjerTwe2i3A5Wu1uy9I+k9frpUrVoGU2Z0ojOg8IM=,iv:CPSgI+p4lYepNRlO0d+3OPHZ0be7D7i1qpQQT1UUu0c=,tag:BtEXbpPvu3ku1I+1jlJhbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
