apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-secret
    namespace: sparkyfitness
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:KSmyJi+Vu0p8g9530Q==,iv:tyojTcfHXsgYqCvsoLMXBPbR1uGcmvmmNbDlKjEMMxQ=,tag:KwwLtj7/HJi641uc5h/44A==,type:str]
    password: ENC[AES256_GCM,data:U5mIyR57nUE=,iv:Q09wRiM42in1Na5ld7sXWfBQxTHINTwiPbyzHvS6Hrs=,tag:P9ZxlbbqOBaGL89zJ7FGeg==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM3NkeC9yalIzUGZYamxV
            THVEQjQ3UGVLL095aTk1Z08vY2lJV1JyelRJCmZvZVZJMldHaGdBZ3RFYVFWcXJZ
            NWEyWGl2dUFzdWcwOS82V2xLeWRNU3MKLS0tIFByVWZIenpMcGpHTGxRTXIrVXh5
            WEVyZ1VySDJOYjhYT2VjOUczem9US0kKT1Yi/pNnEGiSqhhg15T3N1U/kGX3cUFx
            50X7KOtUQTsq/Iw/WCPAQtqHn+wby81JzLs4qjfEDorH1Edm0/Hjxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T20:43:59Z"
    mac: ENC[AES256_GCM,data:Vo60bxQ4WnWiOpHKlQZXHiYVVmmSpo48ENu+dH8pvG03d5YMB4tvN4wAthCc5Vt9BTYYePE9akwa01XtQCkHu/PPub7raU+UtXcQ62IJIsORzMizDS2W5Nd3hb4zeucSZPgT9XQ6nvYX9h5rt3wTN2zF+Mlqd7vq+/EbhI8eyiM=,iv:CvcAu5+gU0qTcS7LmCzxWc9+88VDWTYjz/e0reYDG5M=,tag:Y5hahATjeL9uKlmB+XFHvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
