apiVersion: v1
kind: Secret
metadata:
  name: sparkyfitness-db-secret
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:M/sKrx4s,iv:3DhIpVxM8DqEjffipOeAD4Ut27DViEC69pazKfd8F0k=,tag:EDmmIQz2mMszjeAwZQ7UKQ==,type:str]
  password: ENC[AES256_GCM,data:iirVb1rknRuN6qwpkvm9aq+3JD0=,iv:0NiYd2FThvzqw+nlxY4yW7LmeFZfgRwqDXZqrxBOIcY=,tag:rAHH2url5P4yYnXKWaP50w==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnckFFL1BqTzl5blFGMGdo
        cGFMTmo1RlZLVm1DcGl0clpURkloVEpjZVVJCjlxM3ZVbi9tVWFSZXVSUzkyZVRs
        d0tFVmQ3NzVMMmduWW5PaC9kRk16d3MKLS0tIE9aQm1kcVpNRVZ6TTJaRkpWWElT
        ZklESGNLUERibFFUYWJObkRuUCt3TzgKrfeW5v79EZcbx/X9hEcXNbq7MuJItGBX
        btw0wN+tNrCluIxumNrijyl5wS1ms8K0eojzgj5KEurVsHgD5MG9fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T04:58:13Z"
  mac: ENC[AES256_GCM,data:VZCH6xljnOSkjhtcn2h02TqflpTF19znmR+eP4ms6LAEX6JwGde8aV+rpUdB/mcFZ/c0+13hXWmxsduv3P257h9ngKVgPa5iWilaIxPIOw5a6IsEV1BIv5MhdVzRmltxHVi6uN2pOgTA4bMUhQM8vYotS3HwrG6dZQi0YGdxbwI=,iv:umMmaeNkc5wmU9t4wSMBbL0IM064xUW3QqIv/Sm2A9M=,tag:F4HD/2KP1XDJtV/Hs/3YCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
