apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-uploads
  namespace: sparkyfitness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-general
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-backup
  namespace: sparkyfitness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-general
  volumeMode: Filesystem
