apiVersion: v1
kind: Secret
metadata:
  name: sparkyfitness-secrets
  namespace: sparkyfitness
type: Opaque
stringData:
  SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:kPUYMtxeV2ro6A==,iv:+jc9F30vpqY3rYAr71i9g2OIxkRn2mKjzMU3OqQjLNU=,tag:TFNs4upb82jrQCgTjt7WhQ==,type:str]
  SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:Fel9vkUv+bYG3mnZ/NOn+ZgsfJKviigw,iv:8Y84HMCdNoWYeOWvBNU/XyPzoDEKwoekeJrvR+c+goo=,tag:A0IxYcWJy3tsWvp0siYwvw==,type:str]
  SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:gEUDOIoyfXLWAz1YdGZQ4bLDJ9b/uaA6RZQSs02qAkRtq45DtMzGdn3zkFFJtW4=,iv:kQMjpgtH/4MbT9cHIRbBC8d6yEEx9Qq1uV4f9G0P2+Y=,tag:zEhW/HpY96lfDW9YAW6w7w==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:6OTkS6VPn45DJO6uCwmn3jxTUr04DW7cqnxUnFdgYfBSp435ppqUcSw=,iv:e5++MoERCuxxt0ABdA5lFVzfMNJ1JOl0FUNIzUijohk=,tag:xvfAYnrvAjeBBtOVsJflnQ==,type:str]
  SPARKY_FITNESS_ADMIN_EMAIL: ENC[AES256_GCM,data:FnanwaeK2QoB+N2lz3iU6N8=,iv:XdMkrHxU3e3K2b6PT+gjAOdZVRLNRYbqkhK8OWc9vN4=,tag:j3hJt7a/aj4acMKqOpliug==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OWpWV1YxbW56Z1NQTmg2
        TU84S0NSSWZaR1cyYjRsVDRMdHI3T2k3NTBNCkk2RHVSNS9WdzU2MHYrTGZBK3dT
        cFNjYU1kUTFvUkxMRysvRVlaOXI1dEEKLS0tIDBzVXE2ZUI0c0M2K0V6eVdCWUtm
        ZmdVT2J2bzBGSlhOa0w2YkVseEJxTUUKOfvUZhm2JpFqWu3H6SVCw/vEamJNqeEq
        Ye8pLu/0kkhet+nt8pIvJhJFxN4eif0Dpl9eeNYxNxMoPWK0S7wiFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T04:53:11Z"
  mac: ENC[AES256_GCM,data:79iZqoPwTx5DIeKMv5oEbSXJeUghPM2tVZs97Oa8fE+SUUO8yVl2oF430LCPg4QjyPIY/xM6oHQGjqZr6PHz6gOhI3vr2UOHAspw0KjH3WrodipfiojAbIW7rvQ67PjS+lfAgHVu9ZIPDN7s0VES+6DmzhTsiIjswpteYwUPQa4=,iv:zGhqmzvMXvj6eDjCMxDOXMFmmnXtxR4HMGxkqn9BLt4=,tag:gAUWEgtyLYupRaCb8ilnMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
