apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: sparkyfitness
type: Opaque
stringData:
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:koTIpVHY4FsrMw==,iv:jZVkjknX0ioiiT+8n24eLYELnBUIONTYBG1PTy/GtNk=,tag:q1St63CSKt9Wrj2o8bL47w==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:iescIW0ZBj42OnYsQgxK2pWOVYDlgydTDtK52m/JCIezm8H2H17zEr/pTUU9VH+y2ZgMuY5t7ONyqnTta2HCcg==,iv:751XYhBpPAei7dc0JXeYrtxOCCUeCzOJIjNiiLSVhbk=,tag:53n/bWZI9Pw9RKY4X8W4hg==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:FvHJ6rPFGonhavzWhdTBnLuoFvwF+8uDWh3P9pipLwUNgBav2yOz56bCeE2EkXD3VIT50Ii7ofO4XRD0q7IhkQ==,iv:KSLHi4/9QX1KyU1oHjYDgK3ONXN3GdX3BI7QXqGY1tQ=,tag:Fw2r28Z8N63UiEavV14a9Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:bsJGZEtdSK33fkHsLZE8CPE8XaMEJFznyU9BO4yXLZ/Z+iqtxVP3pTB5Sr8=,iv:PWJYCxJwKXhBPBE3KNKnjUXOQy8TjIXQrQkOG/vFwGM=,tag:PiPntYd5+R+Wn+/jd/P+5Q==,type:str]
    SPARKY_FITNESS_ADMIN_EMAIL: ENC[AES256_GCM,data:ZvjfBmX1zhzl4wnR6icp,iv:pn7TcvPIAW6hD6Rie8H+ns53BBKCSBmTvbjngnA2qs8=,tag:MYM3/PeOPZ0dUuDd2pyZXw==,type:str]
    SPARKY_FITNESS_EMAIL_USER: ENC[AES256_GCM,data:ehaRFkrDXQiJ7flDRG6K,iv:eRHAYm9SErQeoPEDmfnl5PLgifbLQf8NFRUb8qd7Fio=,tag:8sK1YxaGhV/vCfHZlDoa1g==,type:str]
    SPARKY_FITNESS_EMAIL_PASS: ENC[AES256_GCM,data:E9OhvDKji+cVN4VIMVTenNlKE5Wj7QkuZCeAS3qhg5xBRzRqPXvuVAHsKFWy0QAoZQVP9pXIzLmgdO1JwX0ymg==,iv:Ya+XjWpEL7y2LVOJYNkutIkn8cN+li9mt1Dbm7Y+XTQ=,tag:8qPBo3up6QpWeuBQ/Fm1Pw==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucUdmUTJQT3d6S3A2MU5a
            QXBDL0c2N0h5WVczazBXQ0c2RlZXRE16UFhBCjYzY3NRNTlOS2dFZytwWFdrYTdo
            TTNqRy9pWVBET053Q1pPaXo2V2FVcjQKLS0tIHQxdERJZElWMUlIUUNGTGEyU0xI
            YmlzUzR1eXNXUzNEQ2l4RTNvWmJ5TTgKl39mNCk5Mqs6mheT96v8NtM1LrxOQAbW
            gN0KHRfi5LVTTazHc2BEAzqMs3Oecgw67DP27XQeMcyK1/KctrZ9qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T04:03:50Z"
    mac: ENC[AES256_GCM,data:CzAY6tFQ1wwBZ2H92/mPAw+yxsCJbxTKL0xqoXvrocaMEZID4PuJzwhHI+utNJt8ldVsanEFxww6VnxO7TdcfGCLFGaJ+W3zGufpZwMgvY4mdYVIFDsD5UZHj+6EieyN4I9VhHw8sISErdvGa+ATwpN/0xxc1JzMjGXPVgzLcvc=,iv:+SLCcTYiO3DicZvPeZgR52CEnpCqNhx2rTTcro2S7Is=,tag:0h+/ShOcNHm5UAVAcaWNaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
