apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: sparkyfitness
type: Opaque
stringData:
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:3wMjwDtEPveP2Q==,iv:uplViVgvJRTWu9C38iq77/DUatGXiiXG+9RBd5Anhgo=,tag:eFG8BRuiyPsOjSPRjI3PrA==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:3rj9cXbAHMmWJFZy7JNz2w==,iv:M5GzOImEeggr5H6XZ/8UAtt57XPhrlN8vcrOJL0jbAI=,tag:vRAHwe3FFJksaTNYcTGfAQ==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:Vjwc8D4w0XGT9GsVMJDGxKl8jX5F6aaXQ8g0dWXc3xoChvzPg+dDfKnDv4owqDrtauA8xeMPCFkQmjXFAkh7Yw==,iv:ZfeRxr/fj3vwS6hORJ62K/OGsrLviAUidphjLlkUBHs=,tag:IuCds8JuCTHgovXfUOh62g==,type:str]
    ENCRYPTION_IV: ENC[AES256_GCM,data:Wy0HaKlBVOTryCNCmAT+RvUlknyo1j5ar8ES3ZhTduk=,iv:rrSz3mF4udO1GWCPAH3z5C++gQbMZwOTyMSVncN/wd8=,tag:qcbBZs0OfSMqlJXCoHNwcQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:eaXLdNV9ke/MktQCnY1bDd7VpiNhh7UkU2/xD4W3Ww/zAT23eT4U3Hu2yg==,iv:GixWPhP7Qux9OjUAt3kJILEavb2Za5ihzipkP5P6YLU=,tag:POkBvVupCxUEk0g46aSiDg==,type:str]
    SPARKY_FITNESS_ADMIN_EMAIL: ENC[AES256_GCM,data:ZvjfBmX1zhzl4wnR6icp,iv:pn7TcvPIAW6hD6Rie8H+ns53BBKCSBmTvbjngnA2qs8=,tag:MYM3/PeOPZ0dUuDd2pyZXw==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucUdmUTJQT3d6S3A2MU5a
            QXBDL0c2N0h5WVczazBXQ0c2RlZXRE16UFhBCjYzY3NRNTlOS2dFZytwWFdrYTdo
            TTNqRy9pWVBET053Q1pPaXo2V2FVcjQKLS0tIHQxdERJZElWMUlIUUNGTGEyU0xI
            YmlzUzR1eXNXUzNEQ2l4RTNvWmJ5TTgKl39mNCk5Mqs6mheT96v8NtM1LrxOQAbW
            gN0KHRfi5LVTTazHc2BEAzqMs3Oecgw67DP27XQeMcyK1/KctrZ9qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T20:59:27Z"
    mac: ENC[AES256_GCM,data:8LTCx56HrM6OaHGwDjPJ9cbgw/2FOMJ/c6//Q+Vtsp3scE+CEBEZIs7CSAKWJbRBcPUkFwAwcfiCVgBSLgqKuLHfh1yGpEJ6g+RUxWsm3jhRcSahQMMRJuq6BJjkc2IF7gBuR02Uo7CotFaI93itUxd/k2k3eTDq+6JNAVcrPaQ=,iv:uAI8M7mS1xdO+2ipDEZnbPpW95WOT1DBucBQa8VrmY4=,tag:Qq7mNyGO8JNELHSjHg4Llg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
