---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-server
  namespace: sparkyfitness
  labels:
    app.kubernetes.io/name: sparkyfitness-server
    app.kubernetes.io/part-of: sparkyfitness
spec:
  selector:
    app.kubernetes.io/name: sparkyfitness-server
  ports:
    - name: http
      port: 3010
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-server
  namespace: sparkyfitness
  labels:
    app.kubernetes.io/name: sparkyfitness-server
    app.kubernetes.io/part-of: sparkyfitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkyfitness-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkyfitness-server
        app.kubernetes.io/part-of: sparkyfitness
    spec:
      containers:
        - name: server
          image: docker.io/codewithcj/sparkyfitness_server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3010
          envFrom:
            - secretRef:
                name: sparkyfitness-secrets
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: NODE_ENV
              value: production
            - name: SPARKY_FITNESS_LOG_LEVEL
              value: ERROR
            - name: SPARKY_FITNESS_DB_HOST
              value: sparkyfitness-db-rw.sparkyfitness.svc.cluster.local
            - name: SPARKY_FITNESS_DB_PORT
              value: "5432"
            - name: SPARKY_FITNESS_DB_NAME
              value: sparkyfitness_db
            - name: SPARKY_FITNESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-db-secret
                  key: username
            - name: SPARKY_FITNESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-db-secret
                  key: password
          volumeMounts:
            - name: backup
              mountPath: /app/SparkyFitnessServer/backup
            - name: uploads
              mountPath: /app/SparkyFitnessServer/uploads
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
      volumes:
        - name: backup
          emptyDir: {}
        - name: uploads
          emptyDir: {}
