---
apiVersion: v1
kind: ConfigMap
metadata:
  name: invoiceninja-config
  namespace: invoiceninja
data:
  APP_NAME: "WebGrip Invoices"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://invoice.webgrip.dev"
  APP_CIPHER: "AES-256-CBC"
  APP_TIMEZONE: "Europe/Amsterdam"
  APP_LOCALE: "en"
  REQUIRE_HTTPS: "false"
  TRUSTED_PROXIES: "**"
  NINJA_ENVIRONMENT: "selfhost"
  BROADCAST_DRIVER: "log"
  DB_TYPE: "mysql"
  DB_CONNECTION: "mysql"
  DB_HOST: "invoiceninja-mariadb"
  DB_PORT: "3306"
  DB_STRICT: "false"
  FILESYSTEM_DISK: "public"
  LOG_CHANNEL: "stderr"
  SESSION_DRIVER: "file"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "database"
  INTERNAL_QUEUE_ENABLED: "false"
  PDF_GENERATOR: "snappdf"
  PHANTOMJS_PDF_GENERATION: "false"
  IS_DOCKER: "false"
