---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoiceninja-mariadb
spec:
  chartRef:
    kind: OCIRepository
    name: invoiceninja
  interval: 30m
  values:
    controllers:
      mariadb:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
            fsGroupChangePolicy: OnRootMismatch
        containers:
          mariadb:
            image:
              repository: mariadb
              tag: 11.8.5
            env:
              MARIADB_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-secrets
                    key: MARIADB_ROOT_PASSWORD
              MARIADB_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-secrets
                    key: MARIADB_DATABASE
              MARIADB_USER:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-secrets
                    key: MARIADB_USER
              MARIADB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-secrets
                    key: MARIADB_PASSWORD
            ports:
              - name: mysql
                containerPort: 3306
                protocol: TCP
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: mysql
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: mysql
                  initialDelaySeconds: 5
                  periodSeconds: 5
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      mariadb:
        controller: mariadb
        ports:
          mysql:
            port: 3306
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: longhorn-general
        size: 15Gi
        retain: true
        advancedMounts:
          mariadb:
            mariadb:
              - path: /var/lib/mysql
