---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./nginx-configmap.yaml
  - ./mariadb.yaml
  - ./invoiceninja-deployment.yaml
  - ./invoiceninja-service.yaml
  - ./httproute.yaml
