apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-mariadb
  namespace: invoiceninja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-general
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-storage
  namespace: invoiceninja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-general
  volumeMode: Filesystem
