apiVersion: v1
kind: Secret
metadata:
  name: invoiceninja-secrets
  namespace: invoiceninja
stringData:
  APP_KEY: ENC[AES256_GCM,data:gBTlSgerC8fLW28dk9NoAZjU+u3Wmpkj/JYEzyp8hNxATArtHNsCyCU/U7eLTshIyWdK,iv:IG9rp1EgehI1xHHcPPLAZF4qyMJYGJm7Vi29wZkEzIE=,tag:5EAWIDGQu+6xO1GL2Uamzg==,type:str]
  IN_USER_EMAIL: ENC[AES256_GCM,data:hWzMs4Gwt9N0PPHeJorw,iv:AThW8zz/qftleA8oinXaeB4XqgD5e7LVc3MgPoagJG8=,tag:PWl3W7ioEAFumI5un0/N8w==,type:str]
  IN_USER_PASSWORD: ENC[AES256_GCM,data:GTZRoHAUZGD4+DuhR2c=,iv:pX7nJBPwh+LR5Cqd8rTW+MJqoYoEQcEOt1ay7mrAw7U=,tag:OpvlaZr1LQ76UZRnkBmbwg==,type:str]
  MAIL_MAILER: ENC[AES256_GCM,data:ube2bQ==,iv:U58pNYWWF9QOIZcEhVLkGZJqRja9YsrsC2nSc+Nue58=,tag:bnPJpQ97uUEzNsLmKikH+w==,type:str]
  MAIL_HOST: ENC[AES256_GCM,data:k/iLnHrU4/yP70nNm6veTA==,iv:BWqiEqkWXpaYFF2wqPQDbsgU86tyIjAJ0G7dLLKgsGk=,tag:LN91LIB/3ZcnuZy5ZCcZzQ==,type:str]
  MAIL_PORT: ENC[AES256_GCM,data:OASA,iv:OesBY8kuOAmavZUtTtkmIyjqroPQpIsHi4vMObH9evA=,tag:Moz9MN63WHWooZT2/VPu8g==,type:str]
  MAIL_USERNAME: ENC[AES256_GCM,data:f+kceQ3gbeut,iv:2gcz+T9X/hrjrWEPo6lz38IhfAivaLQInXcUTiXGfT4=,tag:NxAogMZi1+5YtHzMZCZTNQ==,type:str]
  MAIL_PASSWORD: ENC[AES256_GCM,data:t7M5vs6DKqyI,iv:B+NVA2KH+bqqAE0PAOYkStC9KjN7DE76c9Hb23WJSVA=,tag:yh0RF272dqzIN/h1WCnzpw==,type:str]
  MAIL_ENCRYPTION: ENC[AES256_GCM,data:LWZx,iv:azRGtc6cXf+f1mtimiWwztLIgk9Urhi23NV8Fb3GyL4=,tag:f2cBpNCytNkn8w4lhcP9Fw==,type:str]
  MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:RbNjq7XZbQo/XSzdUN2eqQ2j,iv:rkhvQBwh+bgq9P9PiMFKQeNeMcC/1Rzg3qh8UTHrcYk=,tag:Jix9t34H09E63e94TubdWw==,type:str]
  MAIL_FROM_NAME: ENC[AES256_GCM,data:fML57y38bLinYrfu/Q==,iv:dprrxcg+nTJK0tT4qWMlMJwS6hOcPXOzHcRtBa6c6zU=,tag:Gco2oQfL6rDwxmEfltobfg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:36qnYXMZPfc5LiwGqprk7F24+ZlWXSFDPtgOg30FrVc=,iv:645JTDZlZl9fgnBRlM4r6c0Kw9LuLCfKuNyk6+C5tsc=,tag:mimirAOQhHgaIu4NtuwF3A==,type:str]
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:OJjybMOnwsgpku+8p/q5F5gk9UxkEitVudkIUeRIQko=,iv:Hczm/BPT6mGmZHSFI6Qt82jd9Zs97NFwyyN86woHqwU=,tag:Wysy95PFSOo4BEQs9TTAPA==,type:str]
  MARIADB_USER: ENC[AES256_GCM,data:B7bbl7I=,iv:jFaBW41Tkv85Yf7SA971RHsxS976RWqkyLpVqdatmK0=,tag:P83MnK8LYqOQuUmcMJ+RkQ==,type:str]
  MARIADB_PASSWORD: ENC[AES256_GCM,data:ncWGWjvO3SHuGBX4Wn+1hMZFgv3VUTidJYRHc48NdeQ=,iv:ZIvtTqKBbL9ITWcBnMfTrIW3LKmDFPvU6R7n0KBqeSc=,tag:LpnmY25tFCZvoc15dWhCQw==,type:str]
  MARIADB_DATABASE: ENC[AES256_GCM,data:WJN1LFU=,iv:4E0GdpJOV6y3mPqiK5aiO7r6L3YH8kE3qyy73gs/DEE=,tag:lZl/fZnQUxXwUPjv0mOmqw==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZTdjYkZPTklsVWQzRXAz
        aExzVC81SS9nM1hnR2lUd0lIZDZKMXI2aFRVCngrVXloWThOZzRlcGJSMUtmazRD
        Qm9ZUjBUUWNwWEJQV2p1eWRHaWVleWcKLS0tIGdQemxucDNaMzVGRmdkRE8yMUk4
        RzZWdnhWbXBKY1VvNnlpUFI5LzY0eGsKL2i4gSjR3S142WktDaVJATXOd3JStXQk
        IltkhM25LTUQ5MHIC43Xr+onTiCzthOiIkuBG3zoiA8NOGPVWGfK4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T07:02:01Z"
  mac: ENC[AES256_GCM,data:Y9Pb+4GkluILWhZj9cPWT3ERUAsfm91wM+jT3xShmbbf7rKOoxemePJ2OCA+wpaR5TjHL6x4nXAxapDK95NZq4cP/uP48m8R2+RdS0qYP1JyX14+gItNhkrEO2WpnzE3EZyBYlHg4TfhblIKq0bGDPPeWfbsHqa52VSwa1YG/cU=,iv:Fdf5O0FXK/0K7rKBGysLygpprQ6e3+CcBsb3+AuTVN8=,tag:hLXBxi63d1kMfMK4B9iMvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
