apiVersion: v1
kind: ConfigMap
metadata:
  name: invoiceninja-supervisor
  namespace: invoiceninja
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    pidfile=/tmp/supervisord.pid
    logfile=/dev/null
    logfile_maxbytes=0
    loglevel=info

    [program:php-fpm]
    redirect_stderr=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    command=php-fpm

    [program:scheduler]
    autorestart=true
    redirect_stderr=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    command=php artisan schedule:work

    [program:queue-worker]
    process_name=%(program_name)s_%(process_num)02d
    autorestart=true
    redirect_stderr=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    numprocs=2
    command=php artisan queue:work --sleep=3 --tries=1 --memory=256 --timeout=3600

    [eventlistener:shutdown]
    command=shutdown.sh
    events=PROCESS_STATE_FATAL
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
