---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: slok-sloth
  namespace: observability
spec:
  interval: 1h
  url: https://slok.github.io/sloth
  timeout: 3m
