apiVersion: v1
kind: Secret
metadata:
  name: observability-s3
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: "GK31561dae75db292e971b0f22"
  S3_SECRET_ACCESS_KEY: "4055ffb83a5c43ef133be577c57ffdcac167c347eb8f57bab4d11ed4457bd20d"
  S3_REGION: "garage"
  S3_ENDPOINT: "http://10.0.0.110:3900"
