apiVersion: v1
kind: Secret
metadata:
  name: observability-s3
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:fCbfPlIHqXl35Yi/CL7kLzdevUYeszS7Q1Q=,iv:8y8rMdTyr8n2N2KvoiE7XqQTzrGMLFdgdEZaiSXMzvk=,tag:X6AIJg6g+GXxu99ZgVlqVg==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+6C7GyLoEW2IJMGbNIrwpRl3+VxT4Pgu6j0aueHMIv9lf23bRi6GlqQbXrZo8Q693rcoKIHoabEVodRej4LZ/Q==,iv:t9OUB2FGFzePTMD5heLMP+SbJCLG3b8Vb+LI0Cs1wP8=,tag:Uz7w1CDZtqABsL7BGiwIVA==,type:str]
  S3_REGION: ENC[AES256_GCM,data:Gcqmc0pl,iv:Kf1+QD+k91H7MNU5ViGffiTkYKwlNopau42crBj2Uxk=,tag:4bAbdVLZUHozDlLOUxQ6bQ==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:SVdxUCrb2ZnXJKh4TKXM,iv:k3aMR9zaC19tLE3+/Ejz5y78tM8WgX//9Rw7tXW7voA=,tag:TwB9vABeKX8G7GEq6HVFjQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcjlZTlJpNnM5N2RwSGVR
        cXU4emNBeGZNTGdtRnRUaG8xNXRHVlJwdFEwCmdKTVFud095NzlCRXlVQjErNHJr
        Sko2a3lhUHJhK1pJTDZsbDgwZEFjOGcKLS0tIEtCZEI2RHg5emFkMjdtZi9uZHk0
        T1IzUWxGTDQyQVdVSGxKc2FuZ2VVZ2MKue6t9VZ8BpFu0fr5mGOGcROHToM7JxeH
        tD17BAQ8FJ3h6uZcYGNuE2rexIZ4pQPyJgHrtE6BdQVDn2bJ5G5VUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T00:43:01Z"
  mac: ENC[AES256_GCM,data:fZsAXbE9ymSgKRMZB9yDB1IVYpjr1WCsTncoXuS7ab4laCL1Uc9g8MGnCsXZJTWw+H5bRlxPfmOgA0fsJGC2ru2rCwz3LKTwHeZqDRj6Ku36IfoVLMAcLvMQuPfqjacFQIKau3tNUCJpNkU4j2Ja/4Y5rJrur0UebrVJJNEg9ao=,iv:5rMWUrCsUS9WU9ST9ZZDQIxTIziQunGQ6g3qW0I44eA=,tag:92aH9jTmvn5Bd0ODywBG8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
