apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:5eUoDB87pgQ3fMf4b+7s0/TjEDmXekapx5sZOU3Mmz6WRTwHsiN+Nw==,iv:dmcncL7EdlmFt9uu9JBE/I46amEoIozLfQQnbGkltDc=,tag:wqUgqj9Zl6o60nvnscXoWg==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMDZiSSt6NTkyYnZoWjhx
        eStTa2pERjV1ZUFkeVJQK05rem05UzZrZ1Q4CndzcmI1aHNMdHZnazJaT21GNGY0
        REI3SFROaHBBNkhPdWx6QkFPSTVOZHMKLS0tIFZrRUZPN3pKTmwyMkx3MU96ZXF4
        cVpGMHF4UnpFZkhQcGJPckJwcTQvR2cKaHCGVsxNuGyWWtAPpQMCBg9Ea1qITenF
        lvvviWpR4HLszfva2nkh2Imj53DkBNAX4VyrHfTcWZcseHJA1q/D0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:30:08Z"
  mac: ENC[AES256_GCM,data:LacM7JT8iVJRtcXSrKlDPLhiifU1c/Z3aUBbAVQXzOasp4XrpPWArRzxILTBW4sq1OG0M5ld4WE9HLHYUgzxwHXHNqFvsvxrW28RSA+Odi/NpWTkEIKK7HmfGTWICspOznZbtjNGeL9mwZGevIAw/BW+Nel9sTlWGc7zJC/s2ek=,iv:TnL0ssemR+9iiyKVAt41IHhM/0vDUoUATNB8bERQ+5A=,tag:SxwRv94+DZXLUWqHzigKcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
