apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iuAYmaMfF0yT/V14zqo0zgvY71YOw2abWJ1BZ6NNefKRZ5ktvm5eGg==,iv:p2MB1zLbLO7PavXQCa2GdI7+PPrfk+uxUba7Q7dRaEc=,tag:Y0Ob8lLQ3pZTOQOcxLpPpA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L0FUWUdGczNhdFl1VjZI
        QlU4Y3lqeFlLZ0VsRFNYVGNhYmU4aS80RFFFCnJiNXRqMlltWGZ4c1QrZ0tOQ05Y
        VEJoby9rZDZZYVBxcTM2ZkgxSEVFb3cKLS0tICtScUlJdVlWcFBFZTNFMHVCZzdT
        VnJqUFhLUFNDVE9ERGVSZWZEemt4YncKazkshqaQrFI9i63a3+h/9WBLIWp88daV
        jE1zLgg2xUS7PFN/cLSUBbaV/8mKBzpgOUzVLZEtzlHvdYRi4aBTjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:27:41Z"
  mac: ENC[AES256_GCM,data:FjHywXN6+5J79LMmDxcKGS6Mc85yKuXBhI+nj5Hfw8hzQvDOoGbJZBBYt7/V9loPe9CrE7lY/w+9zmvPi+NlwIVPmAEX1lj8dfQA6sNSOg/njKA1y4rOTRowyC+cVGLuypvmRnCxGLkj/1iqVSom8K2Px1FI0CO929e8r0FGKFU=,iv:VAd0+vkG8RrrKB9xvZnoC6WZYcMu5VTyH66U06tuM7Q=,tag:LJbg6kXun8jqUi2d/GJrSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
