---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-db
  namespace: tandoor
spec:
  instances: 1
  inheritedMetadata:
    annotations:
      reloader.stakater.com/auto: "true"
  storage:
    size: 10Gi
    storageClass: longhorn
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: tandoor-db-store
        serverName: tandoor-db

  bootstrap:
    initdb:
      database: tandoor
      owner: tandoor
      secret:
        name: tandoor-db-secret
