---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: tandoor-db-daily
  namespace: tandoor
spec:
  schedule: "0 15 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: tandoor-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
