apiVersion: v1
kind: Secret
metadata:
  name: tandoor-db-secret
  namespace: tandoor
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:2dkySs39FA==,iv:bVAaX2ztw1Z6sIAEi0uHTybQcJrRkQMKgdNk587U2pk=,tag:5OeqQJRQlEVBX82TMXUPrQ==,type:str]
  password: ENC[AES256_GCM,data:Bl9oGrWclDMna7Y7Ip3yrksySFECmPNYrNS2JSPtfZYMw86Y9Qy3kNcG9Q==,iv:raCXeAJYssQoFBolsFlFuzob4IjGbt0SAYIocVXY6ZM=,tag:UQDBJWQfHQe16YDDF7jJuQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYWZnRUxLY1pQUjgzbUpq
        Uy90WWhDd1NxOS9OajBFTGg5T1IzTlV0M3pZCnRZYWs4NXBCLzhwQ3ZFa2lMRXho
        QnBBNkZpYU05ZHBsRlRTb3lldWJWQ1UKLS0tIHFTbDBiUUx3MUtZa3BaWjFIeTJS
        eFdiT3RQMzRtYUtWcE9NVUxUVGk3K1UKDEQtv1z4MLSCZDgr3rw59ddTkQbQUmnN
        zdGhY5Galehv6g583tt005LnsyIMNGdRL1c5cN2QsIGh6VYb8PicLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T17:13:58Z"
  mac: ENC[AES256_GCM,data:JtI96F4JaG+u7SOs6DdaxGs2A3nPxPHMd+kkB5091+QDOOc79nR+e88pNmN/PiQ9kJORO37NbO59eSR1g3AJNsApuh2nbm2XaoWw0Ns9UA1MPXsBNhmfjhO0XzAG9EiKRxdxXv1ADLpQi2Ew+DnF11MfDjUgR6r5288MhlJVjM4=,iv:3zyftfTrtdLENUT64LJujfpiML6BbPTV+4FpBNwJ3ac=,tag:kULlUu11AYBIHDnjt3JCDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
