apiVersion: v1
kind: Secret
metadata:
  name: tandoor-secrets
  namespace: tandoor
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:P0mB59JA9YwEvaQpI5MBSXebCejoLG2Ax6faBbePpC2DtbKGwEg4QKadCdgiLyaTM70tDlc6JH4rviIbdvbBTg==,iv:fApLo/aWEPwI4JPfqEEF+IiXDvnBmE2F6ghjf6+23JM=,tag:jaB8iNWKFDHhhW6MC2EEDw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:IhYmuQnYFvKZSF76iqpx/aKMl/Wj954KqF9KUEgsw6Rzp6CR917O/+1c9w==,iv:z/u6zTh03Gdb1aKQHD8aL/xWmgA9+oKzaDl+35sIbE4=,tag:E5p2jaigGemAtBOdW2Vxnw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcVNoZ0o1blJJWFRTaFVB
        TURBcE1xQkxsa3I0L0JFWjlyczUxQzhFakRRCngwUnlQUU4zaXFVdTB2RDN6dFUr
        dnRQeWZNdzQ0MWtVWHRGS1pHMnNDWVUKLS0tIDZLVjF1VGpVbjlTY0tWaFFUVXJx
        eTIwejl6aGtDYlRrVDIxWExDRVU3ZWcKsjJM41vlhNfMz12p+vNw5NVwl8KK0tZS
        PG3+Or4AmbGXoeZXFi0cvShmWTej8+R/YmNKvwsyNNZ7VDTba3DVLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T17:13:52Z"
  mac: ENC[AES256_GCM,data:5Qv5xi8lc9/OLncAYb144QV7Q7dumJPbENilCeeEUXlCCv8jaztPKuJHajUjCpeYB8sM+CbtIZ5M8wnykrZoJxxiNv13HUXHwpU1ovhwT8+3HFzckXGN4KoyFalIEZvDKTrJr3HSidGPI5/3aQ96yPg75mNi7neyhbB5/ADYXDY=,iv:r9PKJmrLVjTvjJTpksEbBaGvfLeG/w1a/jiKv+s4MwY=,tag:tsKuCFRes8+6elYlh5x9Jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
