apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/lEHmtNSwStJcIiDtM8=,iv:hTSlKTODm0Ydz8O9e236yvLAMjeJs/G+5UitPKiMVBI=,tag:Gowytgwp1HC26XyLNdNx6Q==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT2ZvSUJxOC9FZC81Q1B1
        YWNZaWEzaVNDbTFwWTI1RlF3Qis3NXI5VFNZCjF4UGRNZXpoOEpvVGFmWU15SUJD
        NzNkYWRxRFI1VjJGSkhDd1NkelZiM1UKLS0tIGFqNWpoZnk0QWgwcGxtOElQblVJ
        Qi93bVRQZXJ0OER1UzRnRXlqaDkyanMKpS02uYIoXBt341msAUbG6EWv4zTzYS9v
        Y/vXrlFiK+AeSLa1WuwvMl2Cf0/3Pkj3CYUbwsPSffSwLgnzjH6CRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:27:41Z"
  mac: ENC[AES256_GCM,data:/FLQRl0MwkX1OnxQDnZmVvsyHFkb3BE2MsyUi8brCn+B6doBRg+fHCulMZ7MRvAKYD6384sYPH46wJ6nnFxrCDZP70RXHNnvp9xSyDcnAf1K+p/EiSzXFjVm1vj2287Jl5xVcrieEbVjQTXqylODIgCXhfvyuIi0N+BPFhzO4Ww=,iv:Eg0xmMzILWKdfM6dRRbJ5kSWuTgdQuFUxJQnoZvnoXQ=,tag:bQ24++/pO/qcrWTxBNjHFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
