apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rBJAMywLHkjXQl36bpk=,iv:cXONj5LtWGbXPTO8q5x8nTHObGEluS6/XQddhI5Exmk=,tag:p4o3K7CJIjLzfe9tIeptYA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYekNXWkdHNVg3c3J0aVFB
        VEw3bkNFYjFVMVBUUzdzOCt2UUFmUXpnYmxvClJSYmJPNEUrQ1htVUpnMXJHZFV3
        cE50ZXdFckZIbDQ0QldUODd3bGpvNzAKLS0tIE9lNmIvNzBWb0gvNTdWUGdHSFg0
        OFJzWHNHZGZsVmp0c1N4ZDNnc0U5cHcK6ayweuxNpTbO/z0CvTi5IeP+i2uwUPCd
        KwgGWZyFYBmGZNnO9GhW/M3AJYDh9uuKdBz78rYj216FsoSJxX0GRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:30:09Z"
  mac: ENC[AES256_GCM,data:SEoCSAosnSk/nogiXHKM9mTYozelcwyVwHXmQJJf556fJcnezByhdt4g2Hrwttvb3se1dfXlvwTFsfH3CfvHkaKMf6Fp7IPsuZAUAnC07EvcY3ZMBFYhQsA1DiosLINahAz9i7vuwPGVWDF1NOTpxQVhJ7CvPgFiM87Lzgky7vQ=,iv:7VoSdyjkTsECfzx9Xz/wAdFCKZ1/IYLk/rdlLF/bXDc=,tag:O0PNVEnsq5dPUorkiJBVUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
