apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:G397MvnkUspHcQM=,iv:ESAbMdCrqkC3oIbd9yaJt5bQu66eKPRVmQGVE1j9kVE=,tag:OZpa13uPc30KDAEiLUjt8A==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYekNXWkdHNVg3c3J0aVFB
            VEw3bkNFYjFVMVBUUzdzOCt2UUFmUXpnYmxvClJSYmJPNEUrQ1htVUpnMXJHZFV3
            cE50ZXdFckZIbDQ0QldUODd3bGpvNzAKLS0tIE9lNmIvNzBWb0gvNTdWUGdHSFg0
            OFJzWHNHZGZsVmp0c1N4ZDNnc0U5cHcK6ayweuxNpTbO/z0CvTi5IeP+i2uwUPCd
            KwgGWZyFYBmGZNnO9GhW/M3AJYDh9uuKdBz78rYj216FsoSJxX0GRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T06:26:33Z"
    mac: ENC[AES256_GCM,data:wa/NneWIOtSH/N/OKlQ5t3JlpDHXIM6Tgi4VNQdHjtglAh0yJDDESzHXtMtQvCltfzM0qbWZBcyQtltFRAZ5mEjGomBH2NifgNVMHoEPCbhXqHwSGSFDsrgsUAMkRsQ6CCiTGzkmTocnq/F9LMCjiMA2I6BHCBSeG6l/49SnfJ8=,iv:L4CvDFDvX46dwr7gacOCIMvYnH1oCXjWgTT3CovW6+U=,tag:90KMixF4ILEllO+6f/soQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
