---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-general
provisioner: driver.longhorn.io
parameters:
  dataEngine: v1
  dataLocality: disabled
  numberOfReplicas: "2"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
