apiVersion: v1
kind: Secret
metadata:
  name: grafana-annotations-token
  namespace: flux-system
type: Opaque
stringData:
  #ENC[AES256_GCM,data:fBRsWK3tJXZJjkpriImNzHT6iKblp+d2qhpH9hNPrCj3PgModS9/OYIZVD7VxTK4OLDgO/yD9yHf,iv:59tv9a1c0UeKE9QGyQGiUALpC/MO7LJHxSkc3F5IlnM=,tag:k4q5m9Ocb08usgWYNI2ucw==,type:comment]
  #ENC[AES256_GCM,data:gUFQItCzJni2T1FsWDGqVlWg67mz8+2taVkwvKOJh0J4jVzMsc1Oq4YG8H0IacqGswvjbcuD5vGQHdsWTD5ec3C/BPnr+tuj4GGv+tBToHF0bVJugI0k7/kJiw==,iv:YxrADRVy0JMeO3UK9nYxII9XGkv1laI+ESKa3WWO7QQ=,tag:Vb64ylR6K0lyHue6aHNL2Q==,type:comment]
  token: ENC[AES256_GCM,data:3UpIyZwt0KBXJyIwtqR9KQaVx/xQA9KhAHvFyIS2Avu+nhYGL3hCybnDnMPEMw==,iv:F721K95rBXFxRYs8d+JKaPRp1a0RoM7Rf7Orbtwxjaw=,tag:IQUnnhPYWanas3u4b/wmFQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT2V6QjBqMnEvbjJrUTRz
        RDhQUzlqbjZlTVJ2YllPSW9vRCtoaGtJNGxrCktRSVorZEpUN0lRelJYY3BNaUZz
        ekFZdCtYaTZXK2wvRUlHbFAxaXlxOUUKLS0tIEplaTBkTkt0TE1YUmZEcDdSalMx
        eTRvak1LakVyd1BQTThmVFB6R3BFL0UKJLhbc01RKoJMoJC/24I9QvQi56iJUo7S
        zl1j//B87Pg8QTIbLsvnQx2pYJBr4r9JJJXE80PYLIc0q9Zsznyecg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T01:20:28Z"
  mac: ENC[AES256_GCM,data:xDPw6gMaOXNfzQm9af3Mln/L6FE2RJxnxMFjNrP0m/4f8ei5mN9kaLfxTN9nHmuO61pthxVHKu2WBLIg/dPe3tyehQ6LPdaADbEvyQOhRy+pdAxSE6P3bqHLOF3iDNi1QJThRVoTDP4+4UlINoLb4T9sP9zUa+jLT+x31RJc17M=,iv:eQw84FSkqKM9jss+eyMFjBrywQObds/P1mnTrg4gSc4=,tag:lJjSHu8/QTDabAUTLFMBaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
