apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3Nc3v5s/ajOzjZM63v385dIYpkikEbA+XkyIk7zknNI=,iv:JKlKkjijSETDvYR1us9wuPXMK+RUDYjs4sVTU3RfvGQ=,tag:dRnYF4g3ZT6CQCFQxG1VrQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMlJOcGhFVlVQcE9tL1gy
        QjFEeHBrSDkwRkgyb04wQ2xveFJUdzZnaEc4CjFLMmk3UE5JRDZyNkI2WkU1d1lU
        d1hISWN0dG83b29pVkhOVWsvVS9PTU0KLS0tIDBvQ1FxQ1BVdGtibUxmVVRDWGhr
        WnAxMXU0czNDZHZjUkR2QlY4OGdHUDQK/oRAvLMYVED2IB8IdPNrpXnj1OTDdes7
        WVDrFR/yyD4nqrUJCUAP7E/URxBBwqhxesdG1G2savaNMOVkAgWHRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:27:41Z"
  mac: ENC[AES256_GCM,data:IHZuBqAaX/UzU/xXyzIqf0OhmXPd9NHANsyenfzabGqdo5ImxBZD0Wd0fS+czw5qZFhjVHwIpWj4yF36kCmp6T6W5UQW/pRhtNjJmn0aDEEJB+sHmnCtGPYvGglEOkx9WdjzxOjMMxiZtnHW3V9dEuuUAwh1HrpBVOBLbtrK2AA=,iv:/++m5oGKWd9l9VokDElt+IuPJu7tX6aCCBtCSpZDR7c=,tag:+IzCmPDoXROPp6FG4hRc9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
