apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:5tnEfHo5hbDr0IF0d3EX0yljI8dLsyj7qe0SVbWToiE=,iv:8bEKF/7j+17t25uOZc3EbXbEzttg5ROSypda6F6qqLA=,tag:i0jSIPi9JrYFZeub/EvUjw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYTNTaGc4bFQ2bEYvUWpB
        cVNFSGFZbUgyQkxHVllSU1R2cUtTdzIzR1ZNCnFmUXUvaERDakg0cktYbFVxSU82
        OFc5bklxbUlrdHZIcnAwdVIrNGM1QjgKLS0tIFRkVUJGUktsL3U2L2w5d29oUW1a
        bjk0eW5JeVRrRmREZU44Q1N5WjNhaHMKLN4d8csALgto6mSOACir4hcHLKdXg+9q
        oq9S4bzOhsdftO8chC4d9F2ME96cVtwERqBOZITAZt5c7jysBjMQ+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:30:08Z"
  mac: ENC[AES256_GCM,data:naaaTLPRlKW6gTWsgllovjuCVHEpPq4ME0BAHiKpuC/u7T/phj21aTCj5yKQJ4hQsjqC4k0j9lB+tZwwmHXiXTdaheyDyb5t0rHdLQLu/CTKowjLWnpsFUIxZA2cuvQkTcKFTPyTHzm1oSv8SWEY64RjAttvKWjMbowzHjv7HiU=,iv:LK77akZDWvUdj4nDxvllgtHRgJ33x43aA0b1uhyYESs=,tag:OWLVAJ4fe4ZYdy4E0QXmCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
