---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-from-vault
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: example-from-vault
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: webgrip/prod/clusters/soyo/apps/example/app
        property: username
    - secretKey: password
      remoteRef:
        key: webgrip/prod/clusters/soyo/apps/example/app
        property: password
