apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:AwnEtJU=,iv:ldT7TDNbenR304IH6sBlphScVFAuXO9zu11bCTV9ekI=,tag:rg+pdewNap1L3BYvZForWw==,type:str]
    admin-password: ENC[AES256_GCM,data:JvSNXRo5hcBS347ohqIO9Pdr+3A=,iv:OPZtcAqo0ZBpHmSzVrCbMYtr7ZuVdlyMCts0EGAZZCI=,tag:6hVY626H+CDbXotlFwdcEA==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeEZVZVIyOWgzUXdyYTN0
            ZU5PcW5CUkwxT1VVUS9IQ2diTXlwMTdOQmpFCmNEejhTdUFDL1J5Z1FPNGlodysz
            Z04yL0hzTFlIaTBVV0h3TW1HcjN6R2cKLS0tIC8vSTNKY0N0VjZ0ekYvK2JCM0Rm
            MmZGd3p0N1h5blVsdEFGdExnNWhjU0UKTO8jvz7RYplliibjB/ln2MSqm7ZQJU4f
            7+43v+VduX1AzmzGYc3gL01mBNMeJCRMVrjVnk5RxCf2DxP20+X+qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T01:33:00Z"
    mac: ENC[AES256_GCM,data:lm7WL2FFP5GD3ztbDPVmsEuFh16Oj6dACl8aCPKXq7QOt9nyLBtPXnTSTpRHR27Bcgz92stZH+Lj2lrrpVcU5RZ7gFEbQM2q4rQwuMKTmg+CqX6iHHN06J0Wp6uPnw3QUDRLtbE4U7MROumA770t3ChObhad6XlrFuNbSIwcOQY=,iv:pBNYmI4qUtwFMLnjeat171b4wsVaQZ3WTDBRxoRcz7k=,tag:ua1wg7d4lwbJTCe35xRPbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
