apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:AwnEtJU=,iv:ldT7TDNbenR304IH6sBlphScVFAuXO9zu11bCTV9ekI=,tag:rg+pdewNap1L3BYvZForWw==,type:str]
  admin-password: ENC[AES256_GCM,data:kA/ULjaxEEoI,iv:Z9CI43jvcIkGABLZaH2Y4UViHeXLPitjjbp0KHnQEYs=,tag:QqWHSKle3d65q4zRKyCfgw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeEZVZVIyOWgzUXdyYTN0
        ZU5PcW5CUkwxT1VVUS9IQ2diTXlwMTdOQmpFCmNEejhTdUFDL1J5Z1FPNGlodysz
        Z04yL0hzTFlIaTBVV0h3TW1HcjN6R2cKLS0tIC8vSTNKY0N0VjZ0ekYvK2JCM0Rm
        MmZGd3p0N1h5blVsdEFGdExnNWhjU0UKTO8jvz7RYplliibjB/ln2MSqm7ZQJU4f
        7+43v+VduX1AzmzGYc3gL01mBNMeJCRMVrjVnk5RxCf2DxP20+X+qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T04:50:00Z"
  mac: ENC[AES256_GCM,data:fEP/JoSoIFSJG/tUTX3PEnrvjiSrXVYqIvFX+b9kLo8qEQas8mgKwPWif/ClomG5zbMoJMryz64ft6cP4hsWj5swxdu/pZq0J+tDKiqE8rMtsnhQYRBIUeI7hWVox1WXMIFtk9tUtyyJYE+ELogb2DXBARn7lwsaHZXX5Jdzwwc=,iv:1YgIU8E4Gei/Lf6mCgw5GjcY2puWDdpTPYBbYmMOwlc=,tag:/oln9/0OeN5Qjz/OI5I3Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
