apiVersion: v1
kind: Secret
metadata:
  name: grafana-github-oauth
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:RLXcwOLEfGP52GenrVwqe8mT1AQ=,iv:g7E88tUmlKz9JcqmOZvRQZUu/RpvZtCw9SJixNGxEQU=,tag:PVNUeA1fs67mTToYJyV4+g==,type:str]
  GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:4ONs9SEl3za7yloGE/d1Icwh62qLzd629iSY03H8RU/XQHuhUqDOKg==,iv:KlT/MPxcrFlRGx9kXWsDYF29THDGawe+nT7WsSCkIC0=,tag:FDlkAr5xcPq/j//lvLmTkQ==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVXA4MStUUGZINmpIbjh4
        dGtKL3d1WVFLZkdrUmQ4OUpwcTkyem9pZEUwCi96VEhiM0p5MkcvTnhMcDVhcENF
        SGRpNzluMGJVTlU5dFI0T2luYXpHUkUKLS0tIHUwRUdLNGZ4cDNxcCtuZG4rR1lu
        bzJpblZlRE5jd2JEcUJQSzFFbHZKdjQKroUzmWLixepydJohbdL1+vD3nq1kyaSL
        TiFRr+5a74BQxqeWnWuMZz2EvQW1p0YTJUJc1t80AY2Na4Dg//RywA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T01:16:06Z"
  mac: ENC[AES256_GCM,data:1W3LX8oOAKKGsMX1C+GZILEYCjcRJUOz/KPM4usUF2wBp3UMUDx8A/t+tMceeAPhd0NbaRgYrL8LqV7UUfVEP2rAH4s6wlhnhNBsnXV5eUVxMLGvHYL2VP+zaklPa4myUpIYw3XuNYWVx2C/U2s4FCSwNhexixQAqaLoPol5pdg=,iv:vENpmIQJHs36W5IT1Smvr2uaoQl99nQ0zgaWmDTY9as=,tag:046LTu+N3/80z8qsB23rag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
