# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./admin-secret.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./dashboards/observability-stack-overview.yaml
  - ./dashboards/tempo-service-graphs.yaml
  - ./dashboards/kubernetes-cluster-health.yaml
  - ./dashboards/kubernetes-workloads-capacity.yaml
  - ./dashboards/observability-lgtm-health.yaml
  - ./dashboards/storage-pvc-longhorn.yaml
  - ./dashboards/flux-gitops-health.yaml
  - ./dashboards/cert-manager-certificates.yaml
  - ./dashboards/cilium-networking.yaml
  - ./dashboards/longhorn-storage-health.yaml
  - ./dashboards/envoy-gateway-traffic.yaml
  - ./dashboards/cnpg-backups-dr.yaml
  - ./dashboards/synthetic-blackbox.yaml
  - ./dashboards/synthetic-k6-canaries.yaml
