---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap-gitops.yaml

  - ./secret.sops.yaml
  - ./webhook-auth.secret.sops.yaml

  - ./webgrip-gitops.yaml

  - ./github-app-token.rbac.yaml
  - ./github-app-token.cronjob.yaml
