---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap-gitops.yaml
  - ./configmap-ci.yaml
  - ./configmap-infra.yaml
  - ./configmap-apps.yaml

  - ./secret.sops.yaml
  - ./webhook-auth.secret.sops.yaml

  - ./webgrip-gitops.yaml
  - ./webgrip-ci.yaml
  - ./webgrip-infra.yaml
  - ./webgrip-apps.yaml

  - ./github-app-token.rbac.yaml
  - ./github-app-token.cronjob.yaml
