apiVersion: v1
kind: Secret
metadata:
  name: renovate-secrets
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:EhYxAj3KP3aKRjIZbmzFHKHhBsQl74S8107m8YiWAwHwcGABRLwjfmhvIEumlhdfdi8J64HbfxcR7VZN7fw0YoASNLFK7cQcn58Tdp7MjSHPQVL9bWRhdDZaCKD/,iv:f0XaA1LrRx5QLRu2v6YtGWMlPmrG8Tv5hIixXFkFt4w=,tag:wREpThNA3882tOjY2vASAA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmJ5eWNlcHdpYVQxajBW
        VGExMWxOWTlyTlgxVEh5Wk91OTBzWWVpaFFRCkh2ZWRmb2lMcEsrS2RoeHIxbVVI
        emtSSkp6NFRzbDVad05uNUN6M3JxMG8KLS0tIGtXc244T3pZREZYUy9xdzZLU29Q
        Y0plK2ZsWkRxcjJiSUJSb3VtZmJwRmMKAyxDxxaHYfcFh5W2wfO+TvxwxJY9XS+G
        ykJANiLo749653Umrg7A63SlLv9nbx3AxQtvCQ7Y7VXrwZaKsDwKxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T10:25:18Z"
  mac: ENC[AES256_GCM,data:nHPtUkDZWoHoAKxd92q8qS20HkTQ/R+dFYpc2QGIIzDAhvpCwdWk3n5oNpctbSpT9G8boqz6hO26rRzFnXfpNJcf1YmtxVph+BU1KPhNqRRlXTLf9MQwLH3njNjUS5qRKP8sqpsL3je8nVQ+agFK4AA6DRMQ5x4WaIjSAVAwF5U=,iv:1+aL82RQwERoGMk1dlE+X76qvyje2DghYAdw7rYDKGI=,tag:fc8NO/V81qz+abqqWeP4og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
