apiVersion: v1
kind: Secret
metadata:
  name: renovate-webhook-auth
  namespace: renovate
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:3L6nX2hflCCcUHT9woaYK9AH0LSGjvQmr673G/9y+3iD56ko9LYV5IywjrcYMceNpWDO8eg/iGYdT2ERph3YFA==,iv:Qi36PPfITM8CggkiVDcG3D685mdhKWRyaV5ZqWheFEQ=,tag:OJoKuIG4ah+8HZNw6oi6/w==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMDZwcjIxdG9LaWozQXpk
        dm1ZUUE1enJHWmVrZGVxMjFZQ2VzbnpRM3c0CmErYVdxL1lyK0xzMkljZzBrc3lG
        TGhsaWovZzRNRDd1andhL05JdVZzdVUKLS0tIGwxN3hvakVCTEtmZTd4dEp1VFpz
        NFpoTmlHekFyaVV3eWIxZEV1SWJPN2sKjJ4xujrv1xkHCIzGeftdJYozV1tUpiKo
        WEmhODqiP5DA2TcGC2V6wzmtmVo30xMqMQ+ebBZ7aiujdqbsNcyW5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T10:25:49Z"
  mac: ENC[AES256_GCM,data:ml1GF0N4e/VC92cizdDXUxZYSnuYCoCrGJB4T/O7AtAzqVHhhGIEsf/XNxdkOaLkMamUUrQV6vnrmzXOuSC+jbzP8bkqvuv0a+mb9C7Oss+KkKUV2dxhtb1PvPpWZ4++GmY7v+VKpGjoWxypvg1Is6yizGabXGWMdLesAEHthj4=,iv:Jy+52sJLsOQNY5NFja+6Bfy0Vm7W/kqEyfTlGxIhsrc=,tag:6sT6qaRxsUe1Gkg5x9oL1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
