---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backstage
spec:
  interval: 1h
  path: ./kubernetes/apps/backstage/backstage/app/overlays/with-backup
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: backstage
  wait: false
  dependsOn:
    - name: cloudnative-pg
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      namespace: cnpg-system
