---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-grafana
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: http://blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://grafana.${SECRET_DOMAIN}
      labels:
        endpoint: grafana
