---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./vault-transit-seal.sops.yaml
  - ./vault-kubernetes-auth-rbac.yaml
  - ./vault/ks.yaml
