apiVersion: v1
kind: Secret
metadata:
  name: vault-seal
  namespace: vault
stringData:
  #ENC[AES256_GCM,data:Lbgo9FeOhG/i7/CsfXaUoEelCVQtppN5zfg+EtU=,iv:wbUzL5HME8ekeu5fbpzeAoVZq5syp1D9RdSOPAebCsk=,tag:1mq64tYRYuX9n1uWFx4tEA==,type:comment]
  VAULT_AWSKMS_REGION: ENC[AES256_GCM,data:ABuikkD1xojs,iv:Y+xSQIRTUovP1BMu5tEc0Xsv2uub0e+z4ALExkvkf/g=,tag:M23FTy40mVTLy/VD4p0RGA==,type:str]
  VAULT_AWSKMS_KEY_ID: ENC[AES256_GCM,data:DZe+OwlqctfRi1AE0fNxvXG5Xhctr7VSfYnP/e6RlzNL/Tn9W5TXKfOXfM1seiyTSr7XA58W/3sNBEbPPl4/n7pe0Y7EmNAUq6MO,iv:PqGQgEagvZDYeXzbrmVeQvSG9RxyydiOTq/3gyHB25o=,tag:6SfeWkml/6oXCeoK3ymLTQ==,type:str]
  #ENC[AES256_GCM,data:1dqeGKHuIm8yqBfW0aOCmQjs75zNWMp5G3VQwQGXn7XdWs/MGDG4xq3bnximiSF4wg==,iv:CUm8aanScOUIi/1u2hDaT3NQGVFkh7MMzrx2uG00S5g=,tag:/l9mM6PQ78T+I05e7VCSNA==,type:comment]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:22zM35+Q/7w=,iv:+dmvPN2gApXALWT7OzHomlbWhcoy3ORZbV6QR9Ijpq0=,tag:rW2ByUzEiYS5nueBMOOkKQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZIbg4IxbiRw=,iv:3q22hYFFo6D7ZjsoWQZ41As/phl9aWYVkc1vtFSy95U=,tag:BYYfaC8TM4j4GOpuCywx9g==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVlo4MW1qNENhdFd6NWdn
        ZWo0Y2N0NGJSTjFCZ25GRVhhKzJYR3VQbEhNCnRWcTVPc3crczZ2YURDeTRxcWtI
        TytiMDJ4am9VNGZKTG9lcU4zbjFoZjgKLS0tIHRsaFRtdWRBU2pJdCtVTyszQ3pz
        UjFOVHY1V1hoQ044a3dLcHZZVmY2dVUKrXwkTkDa9rvoTD2x2h7p3zqBqCySY1N9
        ZsCm4uNaSNfDoINeYWgXOIJTZKdf/Pw8yjWa9epJIZm251IroT53ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T03:38:32Z"
  mac: ENC[AES256_GCM,data:CbAcTklvRggUVhIHqw2HmROU2gsRM3AIV5WM/VSpNq5kkuo/1q0IeBij4g+Uq8Q/9kFiZB86JGMxzHeCkK6LCJb3IqOv02wYmUJ95Z8HCsWOOCXmneZlIQmyumlt3pM1nQiRQEg1IwKEPojBCK6JZBkX5XHMm/FPU6ebTbKv82Q=,iv:+9ayrOyzCnouZxgYrdlc+C22Dve0JZK3H/Mv7yi2OnY=,tag:xLuH4frs2SAMvUJnq/JdnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
