apiVersion: v1
kind: Secret
metadata:
    name: vault-transit-seal
    namespace: vault
stringData:
    #ENC[AES256_GCM,data:3cV9T+s8gsFf1aABIC5OK6HzMXMV1z63H9IfY1p5QIGQmKVqzQVwK3cWHagmfKVT,iv:1dBiwA4yOB8qpaZuTykuisECb4v3X86mWeROEqXaFyI=,tag:Z+9rwsRc9aAUglEvcxBVPw==,type:comment]
    VAULT_SEAL_TRANSIT_ADDR: ENC[AES256_GCM,data:eCyqmQssGg0KSMeGBVqxGvKIaLy6SoAul9cWyJStF2YvZvmjBJ7mRVw=,iv:rwEbxAYWrcKDPmo0d9d5BuE1pacFy5ouznnk4P2xAtc=,tag:ox6yXiUdI5k5zX2NHkWLLg==,type:str]
    #ENC[AES256_GCM,data:wW3fufu5rjf087+H65/0PBvgc85eOG245DfeESdjT8Kh7R3Ge8t7V2qsrqbd35lvtx+nQ08MUCrK3gYP,iv:GvFKqKJ0BQUl1mYcee/pu7a6Un5makdgiZGbzlv+UT0=,tag:jKqrrJTfUGtylEmRk/NJlg==,type:comment]
    VAULT_SEAL_TRANSIT_MOUNT_PATH: ENC[AES256_GCM,data:8is4UrqjmQ==,iv:w5VdlDETRXPi3Eij3iOhQaRLcjGqQBAfQ9Kme5exkmQ=,tag:6hUEfKgTYDMJ+EBhSbeuFw==,type:str]
    VAULT_SEAL_TRANSIT_KEY_NAME: ENC[AES256_GCM,data:pkyTX7c43tW1GrGp,iv:C6J+ySqIkCjGTARxZUCyBZFw/HaQ8vMIde2vIeba5/I=,tag:BoP7FySVQdBT8zTC6+dE7w==,type:str]
    #ENC[AES256_GCM,data:/KvHB2fRnT+RT+DQfhMWQduiEaKoBtf5aFsIl3pHUWxtAusE726PO0c23yHDaqflWbN9ysHmBq0s0tI14SdtkuQCBw==,iv:Or764r/VIKNk8SeKO03jk3xe7IoEcxjnSJn7+EoFGmo=,tag:0sl2F5M10jFh9H/fCVX9Ow==,type:comment]
    #ENC[AES256_GCM,data:KKySdQc4q7YPKF1gTd7BSL6DQTBqnBnGEL4U1+WPtuhfOaGIl9IUGNywc+OEXyO+KXQysdwv,iv:jJDEuk+7mbscY0SA5ZYk9XuNosWqZ+8+6rjLZlb/cIo=,tag:v1yNzrswl+39RfEiBa2N4g==,type:comment]
    VAULT_SEAL_TRANSIT_TOKEN: ENC[AES256_GCM,data:b+znxhzY/5HuPTcyWgHQHeVfXw+bO27ziep5G7fX0zZmSdobOUacY2mXuIPvPce9VNlCS6fVyMNOF2Y/Jqn9Tv7c4tIVLu925EnfzUgMFlLQWXWkjyI+iCkLnBoQvpE=,iv:0r11FBXDIABeD+72L1HNXlMwxy1kuZEGlYmb+9FsWQY=,tag:BMQ+Bbedbk7EihH9U41Zgw==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFK1JjNGpKZnFIQVFwa3Fh
            emVFZnlXTHhUa3J2V3BrY0FQQkdKK3dVc1F3CjdxYk91c2pvdnBmdDdBdGZjYTNQ
            Ykkxa0hTN1Jlc0dLRFk2RUVwZUxRMXcKLS0tIHJVZWo0N3U5bWNndHRvTm5pazlB
            ZTFqK1lLYXVuQmZpYmtSYWtHTDVRUE0KeSYqk8ulev/rkMQehrZXNAA96biZk2Po
            bw38PbXWXK42kxWcfOHhIp7fq+EjMFww43+l7nMKVO5+bkV/9+++Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T20:19:16Z"
    mac: ENC[AES256_GCM,data:qQJJdY1eFgaYFQVq5H0y5UJFSAN/LO2MIRiUcwsN2ZnuG6zCU0crLeYBjuQJyWhE52wWjWNxF2huwqbAZtRTU2oW08c4quXGLohb/quzituITufgzPrsiZE3/edvpQu0hBODRwO5Eg5qMwqV9Xs1YEqlwk3lziQw68t7WRu4VB4=,iv:M9AMqkfyJz6mJbJYDcCU6UAQgDBe0Al9wsdn97z3/fU=,tag:BP8I9ZyWKG5ISnOfqVBB/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
