apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:SsLFS7ow6UVK27sxiNgUnvZjErvdirhk9Fav3ErcAGOa+MsuiEp0gYsPCuvs1SJtH4UmH5ATqQCpB8teTMap8Ks4gZeztBJFrdkVdfu/KeqdhEKle+Je3Qob1A6ze3VZO16xoHlEBafeHVK9fF5sjHzIoqGtRmeN+1fECtt5r56hPXJVVJg+O9C6gUb7+lifaVa2ZM0mNShYsMpmlJXJuwwyYI0qL9UKnN1nI+LL5qUis7w2,iv:7nA0q1RXilgNae2ks6S+BRUCVjkUSCKBwIgJD9aihr4=,tag:00KHVKA4VkiCiGEFRIBuEA==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SFBmKy9YREl5WDVheFpM
        alg0bUpRVkZYWEpCbVRHMTV0ZXl1enJCUFg4ClVQSFprR1dqby8xUTZtSnBRVmJp
        SHpkNE4wUzJSRWhrTGVxOHVvcldNOEEKLS0tIFVRc0VXNUdPTXRoZXMvVU44bng0
        c2N1ZW8rN0RxQ1Q1aG91cE5XNE9OZ3cKzMjGIiR/1fnfZP5YM9fzxa11NtTuvXKQ
        7JJXf8i4kgl+PaZ5R3Z7oN/CPGYUEZcAtd8gE5SP9n7QruFIVOStTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:30:09Z"
  mac: ENC[AES256_GCM,data:PMFPkpbGnAM8N9X1cs0qQLuQWpSc2KYD8cQOtzlQzow9SXjKJw7W8jacTOtrzUGJpaTUaA6N1FQqw9V3563IOYvZnx3QAnaGqCcIuE3Xp0Egm6eS8Zr5OoNk0O6MgYFmMAoMUCzWqDlUoEw02+EoGEMWSJvdRXkwL0qqZ4Bg6Hw=,iv:iQ27QzKXuBG4yl1hpIjhSnjNNDtQabpsmOHbsm0QgeU=,tag:pOLoTClm5kBXb3q99rxnfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
