apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:K064CfmAv08r6QJvhP4w+K5mSgVMDSAGPNxf02q6wVlxqfX8txX8e/UvxGEGt3r1XSdfV7dhpPBXpmEfHnbfniORIk+9y3gR4L+E1jHS7ohA8JqEvyPM3gpFk/PUIU/Tu+Ld+xdvbIKDwy8W3JvSkMo39bqD8Ou3erof46DhGYRoJayOAld8oabLIr4OyXq0HIODlT7X8gZBwl7izPLNKnQIhAiBldlPVlhQtY8hQFeoUkPj,iv:An7toxDFxseCLnJt5yx6Enf2PZf46WngzM4BJ77ZXD4=,tag:481SVjVmumPDlJSN83OGWw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM3g1U2N3dk1SZ1k4Tzc0
        eGd1RUpDMjB5VEhtMHV1bnMrOEJUVW1CL0dVCjI2T3dPaEM2cVdiWHpwRTg0MHdS
        d2xwMWF2cTZObEN3S2tvOG4yazlHZWsKLS0tIFVVbWlMTTFFYTB0ZkFHdXJoM3Bl
        Z1grYmROTStqMmNhWDk3cHYzN0VIUkUKnwGWYebtHCi3hLCWlElVsr1i536aCWbp
        Qn275FQvKyHOXFG1cG0F+tWlYl19Gw4Fo23wQdbQuaCCGxIqy+60dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:27:41Z"
  mac: ENC[AES256_GCM,data:i0MHwEaNQnhZSJn5+C212HiSlaI69ERGIo1JCjukNZfEcJDd4bSr/09fY9Xz1BlykzX6JfQoEJab4SDSKUpdXqTsYxaFQyXNKwTbDEPVtCCXqxDPDPLpLIAKKQ9K6YxboGUyDSkaeLpwpPK+4XLMygfF3caqVh9dnXkiCMu6Tag=,iv:BEQLOJ1q1LwuNNW6/TDkJIftqm+IxBKAGlYurAnQg2c=,tag:dQNj+BKdIS1M/vMh7iAqaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
