---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./db-bootstrap-configmap.yaml
  - ./db-bootstrap-job.yaml
  - ./ocirepository-app.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: freshrss-config
    files:
      - config.custom.php.tmpl=./files/config.custom.php.tmpl
      - config-user.custom.php=./files/config-user.custom.php
generatorOptions:
  disableNameSuffixHash: true
