---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./pvc.yaml
  - ./httproute.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./postgres-secret.sops.yaml
  - ./database
  - ./dashboards/apps-freshrss.yaml
