---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: freshrss-postgresql
spec:
  interval: 15m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: 16.4.3
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
