apiVersion: v1
kind: Secret
metadata:
  name: freshrss-db-secret
  namespace: freshrss
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:DjLrRHyU8y4=,iv:AaYONRa2IH2hEwsoPRh8GeMWrmvFWcJ/QQjM+7fG4Z8=,tag:FL0XQCovL0EE/IGGjYrMmg==,type:str]
  password: ENC[AES256_GCM,data:o1++24PFdww=,iv:/d9IQqunCD1VpM2KXGumwQwgc71nJcnwNeqBcKGk38o=,tag:uBA/CWA4FA7lbcK4K3soWw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNlllM3RhanhCKzVWcXgz
        cWN4NFVvYTAwUFFpOTNZZEQzdndRQXBqa0RJCmpxU0tBMmRqb05zS004M0hwV21J
        UE44WVI2cktVQ1JaRGxzcE5CZURmbEUKLS0tIExNZS9QVUQ4Q3lQWUEyeU1zVlhJ
        bmZQWk0zN2ZSRTlscHc2Nm1JUjdWVGcKv4zkXKsexK37bEEzFDqP4OvqKDOIMsU3
        Y/CtYw58m8s2dNwJ4p/UpgD3GpP5WpCtkiEqF9K9Q+OA27B0EK6PtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T18:52:13Z"
  mac: ENC[AES256_GCM,data:nsT4SPgv0PufHbWlGaYxF2BhvIWfLz4jSQwwxdyK6pOJWeHHNFIB7M2XlS/7cMiFXQcq789+TUadjab1Qn2UYqqAxdVH2FnNlp5C4wImJBPeHRlHK+eyh0spvF5+G4d83ZJfyNGp3Y/ceR0NuWK3lP8CTNz+i4BGm8Q0joGgYFM=,iv:W4bcEoCa1nBJkT6DxjMdyCs3irHx/bBtDtW48ps04xs=,tag:W1N/RzJ/Apc2O3TsT/Ap8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
