apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secrets
    namespace: freshrss
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:DMF/fQMowTc4,iv:GcVTzTY5D1M7TYKFNe+Kdmo2gw+eEg6oQAnu3u9NZDw=,tag:EEqQqEkx/iqwTQXIAH0J1w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:cVHmOgmD5Ms=,iv:e4toj11ymz7jNpVCfOBIKzRQGsj3pW47Hb25qFVgqRo=,tag:OSNptqiUD6Cg4J7WwXEJCQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:0y3bRwe5Duk=,iv:uVt19HwmfRRymNureu6SN3X+DpsqPzHMsCkiL2zDxtY=,tag:uh4bqoOu+j29R2a+1O+sgA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yt64jlDll24=,iv:H2a9ztNAMofRvlwOY6DRrM7vkZumSf+z4z9qKyaEC2A=,tag:etXkc6ciNsMqlKHgleh+aA==,type:str]
    POSTGRES_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ejBs1nCI/ZkIx9bOOSk82ttsDTY=,iv:178LU05JDEg4SOvNyJIxCcZ/GB3u3hIC6l6bg381CRs=,tag:RLf9+jCDIwNRIXw0HoTO7g==,type:str]
    FRESHRSS_BASE_URL: ENC[AES256_GCM,data:bvY9mwQLT4regZKQ5/YagjIMqkrH77zDbezehQ==,iv:W6DUBW8mT+Pp1fTTiGXdxnRMcTFCNCyLYuB0TKLGN6k=,tag:dsJicwtgy/SXbZjygMv50Q==,type:str]
    FRESHRSS_DEFAULT_USER: ENC[AES256_GCM,data:Sokg54eC,iv:dfBJ10ajBGrW7LAXgS8qhfF84j7NwbbuJwPXtIpuY2Y=,tag:12yZLTlbDyvrTsWED5Ew3w==,type:str]
    FRESHRSS_ADMIN_EMAIL: ENC[AES256_GCM,data:uwqGB2cqE9v0+S11m6xyU7A=,iv:ITFTOEzo/hGcI7vp2EyA6/lztC1lLN4Vh79sdI1jV8s=,tag:dcMlwlNTDbG+8OpNTS599Q==,type:str]
    FRESHRSS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lJomx0JP2h8uFljBMoo=,iv:I6KB/k0fVJAtQg0S8CNuB38MYnPF4vgCv4Pf7JZ0mLg=,tag:JC4purbIdVr086lAgnbc6A==,type:str]
    FRESHRSS_EXTENSIONS_ARCHIVE_URL: ENC[AES256_GCM,data:ivI01kJ9FDBAAmbqNEgW/ohx9PjU/uL8UqlAId2kJVRmgXOvrgsZMqQHXyEAbzdCWc99HIcKjdJaSwj+kSOTY8nzsM4hsGo/Ypf3LsqdEg==,iv:8jy2PseV+P5V8S4MLLh0cwAmcqWKI3o7C5yhp1BFwxk=,tag:7Gy/UN2UJLrHw8gAxmV05A==,type:str]
    FRESHRSS_EXTENSIONS_VERSION: ENC[AES256_GCM,data:ip85Y/lwosqZMDk=,iv:+l1aP2UA9C7bdgS5X+F2hNeFbRwjn90r+/6Wks0D+F4=,tag:V820qg9TAO35JxTuCpX28A==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb2t6R2lTbjk4R2tra0dM
            VVBYc3ZJcXF6cnF3cGR1d2oyME90MWhPRjBBCnBWcVRBMDJna0p4c1hvNk1ORkZI
            anJKSVR6QUpTSkRld25KeDl6bXg5NGsKLS0tIGdlQUZicnBkUkFHb3RVV2tCTnBj
            UHlyUnN6eHBtTXBOem52VjM2SWYxK1UKhcDjjW3kovm/6HdDkD5SmIb9yzPoeeIS
            thhYiGg11CFP3K6yLpdpvLnU038fQX3YjYUjzDe//2ErcpexwDDcsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T08:24:45Z"
    mac: ENC[AES256_GCM,data:L3DBJRc1tEg18fQ46MVrAlqYsejQ2+aGL46bsb8y8Ko9xABT8KFJ//g1mVE/OstFGOW//lRIA1ixyKQ8ukJ89WHQM45W3t2GaE6c+lEOk4RDXEQWijpL5B90JF49VueEcAw622ZW0LfPW8r+TwdnNDiQ8hIrayKtxHoI64H5JC8=,iv:TmdhwNoJg1PtCmwHqBGwFYSVHZehA3cZK8XYcvIn1KM=,tag:EtrqdPGeW5knSKNcROR/3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
