apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backstage-daily-backup
  namespace: backstage
spec:
  schedule: "30 3 * * *"
  cluster: backstage-db
  retentionPolicy:
    keepLast: 7
    keepHourly: 0
    keepDaily: 7
    keepWeekly: 4
    keepMonthly: 12
  startingDeadlineSeconds: 600
