---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-restore-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-restore-test
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["backups"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-restore-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnpg-restore-test
subjects:
  - kind: ServiceAccount
    name: cnpg-restore-test
