---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: freshrss-db-daily
  namespace: freshrss
spec:
  schedule: "0 15 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: freshrss-db
