apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:c80XnGWnE4DDlflubj07vDxVc1dDF0Va9WMPSYYyGu/aXCrNpqEpkw==,iv:ShgC7oJajdnincvM4uG8o86MAq5mdKpim6s02WaWP5c=,tag:0KTfdLdTRG27oQzF6w0MGw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OW1KZjRlR2d0dE9DL2VJ
        bTZTZ01JV2R2OTJJNzAvaXV1ekQvRGNTL3dZCnVXU2l2bjgyeFRBSUdiYkJkNUly
        Q2FESjh5SERvZGVPVTM3Slg5Sk5aNUUKLS0tIDhoT2U0MGljYjlLck45Ukw4cU53
        WVlRREhQWTlEdUsyUVFvZWxJbzFmOXcKcEK2yK81cTzmnGHuOBo7rKUxSYcXlaf4
        Qre7kf0A5h6LC9IAianZYk0D/7Tzfa2rU4ALPpOs6WqB82OcgdaBfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:27:41Z"
  mac: ENC[AES256_GCM,data:rIKKPH08LuCcW6nj+B2bb26cvZTXWOON+TMFc6nkRatx4/SzSPTvt7hlZoEmIk+A1rV690HTjIZh9TgYXTHnyDO242+NaPXlDL0rE38dnBe1KW7iWlqoQ4qvAt2IMZaFgIYyyYAsrOoi1UgUEi6ncJKo6+IZ+5UxPsSNK6rtFfc=,iv:Hu5T4Ba/YNRptW0jG8HsM1WJyO8yz9wzS3mpfmUq/mw=,tag:u9BRNi/ijyH8OKG6qHzKtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
