apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:myYMnBe8w8etcuOE97i+1CkrQ8VX54Y2U4or48Vbu4FC8NHlyzKHUQ==,iv:Ju4OkFrCwXxLHTh7XTXYuacuZNPI81RTVK+MBELQWn8=,tag:ywrISnn2qr2GxxHZI8Lcyw==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcEdtelFnNm9GZTlzVkFo
        SWRyeDIyRk1YL2ZXV3Mxb1NxRkVKeXVuam1rCkZ4azJSWWwyRkpkNHk3Z2hlZlQ0
        cGwwR0F3aWV5eFBNTzY4UG44RFJYb1EKLS0tIDdJbVJmTjZlQlNnQzFNYjQ4RGZh
        QmVoQXJvSHlXR2VTK0RIbVhCdW5mUDAKm2og1B5ZsEiQNmxCbM1FLrzQR/OF+Dq2
        YEEGeWJb5cmZTHZeAanNsqJ68o0q4Y+wC00VFmn/axngtXg0vUtRUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T09:30:08Z"
  mac: ENC[AES256_GCM,data:1IFQwEigd/lqNKtTpMmgbeTcIWhn3YH5NZQ+s8+4DQEnxfaPKoHVlubKUZ3Ic0Q1qz7RBIZcjJuk3p9IG6bGcICfojYh9nuXG9I0DNd5WFl2GMa1/W86kIHRI4C3WdWOB0YW1Ug9aZx1kThhIonSZsscZAQ7o5KeExF/Rs1mhd4=,iv:dOKqMQQBkBV0DmG8xKcBkHFD5hG0BlMun9Fg9Bj2uqE=,tag:d4E+YWl++/usSVzd7+r9iA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
