---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sparkyfitness-db
  namespace: sparkyfitness
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: sparky
        ensure: present
        login: true
        createdb: true
        createrole: true
        passwordSecret:
          name: sparkyfitness-db-secret
  bootstrap:
    initdb:
      database: sparkyfitness_db
      owner: sparky
      secret:
        name: sparkyfitness-db-secret
