---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sparkyfitness-db
  namespace: sparkyfitness
spec:
  instances: 1
  inheritedMetadata:
    annotations:
      reloader.stakater.com/auto: "true"
  storage:
    size: 10Gi
    storageClass: longhorn
  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: "all"
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: sparkyfitness-db-store
        serverName: sparkyfitness-db
  managed:
    roles:
      - name: sparky
        ensure: present
        login: true
        createdb: true
        createrole: true
        passwordSecret:
          name: sparkyfitness-db-secret
  bootstrap:
    initdb:
      database: sparkyfitness_db
      owner: sparky
      secret:
        name: sparkyfitness-db-secret
