---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sparkyfitness-db-app
  namespace: sparkyfitness
spec:
  name: sparkyfitness_db
  owner: sparky
  cluster:
    name: sparkyfitness-db
  extensions:
    - name: pg_stat_statements
      ensure: present
