---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: sparkyfitness-db-daily
  namespace: sparkyfitness
spec:
  schedule: "0 30 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: sparkyfitness-db
