---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

components:
  - ../../components/sops
  - ../../components/cnpg-monitoring

resources:
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./plugin-barman-cloud/ks.yaml
