---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./arc-systems
  - ./backstage
  - ./cert-manager
  - ./cnpg-system
  - ./default
  - ./flux-system
  - ./freshrss
  - ./invoiceninja
  - ./kube-system
  - ./longhorn-system
  - ./network
  - ./observability
  - ./searxng
  - ./sparkyfitness
  - ./tandoor
