---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-db
  namespace: backstage
spec:
  instances: 1
  inheritedMetadata:
    annotations:
      reloader.stakater.com/auto: "true"
  storage:
    size: 10Gi
    storageClass: longhorn
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backstage-db-store
        serverName: backstage-db
  bootstrap:
    initdb:
      database: backstage
      owner: backstage
      secret:
        name: backstage-db-secret
      postInitSQL:
        - "ALTER ROLE backstage CREATEDB;"
