---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backstage-db-daily
  namespace: backstage
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: cluster
  cluster:
    name: backstage-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
