apiVersion: v1
kind: Secret
metadata:
  name: searxng-secrets
  namespace: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:EmAfDFp95dtTRvIrwOHO0XbfCMww7wDfX3xvIFYhbB4FpDlLc5fSMxlCwCS8Rcf4ZofBRVx+u/Tz1j87YO7vzw==,iv:zIppSh52Lm/Aczi3vb+g6slHdvz4fZz8w3lXy1B/SvY=,tag:LiutA1KM5maCK5qPzpVWVA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWg4ZEsyd0RTakxTSFhR
        bXpWUFlkNW1waDRYTkxrMGlBdnI5QlhFMHhFCkNpdmo3RlFlRkNpQzYrbHloRDRH
        Z09UR0pOSVlmNjJOZkVhY25BbzlhblUKLS0tIDIwNEVtbkt4VGcrSXJIZTlRb014
        WFNTQllxR0Z0NGl4cnV1Qy9waUFBRGcKTAvkbPRO53LDFmTrbKq4s7dHT2njnxrO
        21mfahDXe6iE0UjM8Cqrid1lu1OWgmG8oc0MMEqNFld84f3ghtLfkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T15:26:02Z"
  mac: ENC[AES256_GCM,data:7jGAW+tdn9xp39Vc1mQINfQ4rxyJdG7FIV+AU9VwSgzbyIiPsCw+6L4tH01kZkv8fxeywQKOF5heYY6E1gstpzFlMOKzRFpObiTmbSauL+d2gNeC9u1U6H0CY4+a45+hVi52FrA8cGW8kSkRz4jCnBhUTwPmp5a5FKr/Wj9Xu7g=,iv:Xdvzl9lk6SJ3/A15J+q68uYdRoI6FwqeTeVkGX56lUQ=,tag:9C1HjTPB7GVCsxhaEO+Nxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
