---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6-canary
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k6-canary
  namespace: observability
rules:
  - apiGroups: ["k6.io"]
    resources: ["testruns"]
    verbs: ["create", "get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k6-canary
  namespace: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k6-canary
subjects:
  - kind: ServiceAccount
    name: k6-canary
    namespace: observability
