---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k6-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: k6-operator
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts-k6-operator
        namespace: observability
  values:
    # Namespace is managed by this repo already.
    namespace:
      create: false

    # Keep CRDs installed by the chart.
    installCRDs: true

    # Prometheus Operator integration can be enabled later.
    metrics:
      serviceMonitor:
        enabled: false
