apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
    # Namespace is provided by the consuming kustomization
stringData:
    #ENC[AES256_GCM,data:/AyB8dhhW6HLE+mcWq+Sj0dPdAe02p3AeM1NuiwvDfCFXuXUb0qyEjnI5LBfwPDZRxzY9w==,iv:KAqxPPa27DrbwJOvJuHx4PrSFi3oh/t9RrwZWYt6Ps8=,tag:robuFYeb3apm6t1cHeOYSg==,type:comment]
    #ENC[AES256_GCM,data:4sk8sdaZyBWY27bAcxrDzMFhnGpgUKtQgghHtWctX5/UjMTA/NKicCD8SXquwen3hLSUlQm9lLeO6ARYZdXUo346WOPx,iv:cGDkSB1wsgPXhvukJznArmajySjsFcJnUjzFQJ5Xwc4=,tag:cmdffDdx+eBxhl7CKJjsKA==,type:comment]
    #ENC[AES256_GCM,data:MTRQKwLISxxuevoG5nPCFK7r/e56zXN763V7B35ucQrdsX59DfJahGbPBEpGUquiULW8Hw==,iv:Af2RFfInFgDl1ks3OtxvcHK4R4P6755ELZStO/Bz164=,tag:eTAzWxhULBQibx+OoJCVLQ==,type:comment]
    #ENC[AES256_GCM,data:DLKlRM7Me9/wBgNT++gcb7xWyF7mzIPHxQpjPvr/Gtx6h1gL4Ryt56ehyAePaMpjHri8/qIUTVWrbfjyUudlplkrkLs=,iv:Ae5hGR5111AvhMOoyhyfU7dGc0jc1SHYsoOplUXLwvU=,tag:DNEE1VnZI8MvhXIgmDlXzQ==,type:comment]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:ELwDrwb9P8tCuA==,iv:a0sbn03dPa4p6UwHRO/X3n+H+Zr+T4+o90ILiuKn+qM=,tag:4W/XA3d203+lbqaWxPCwfA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hma/JnVzssnhTVREGw==,iv:llGDz9tEzunm0yS79UI6ADZ7MABDa0sGPlFPyTevjms=,tag:+bfJFsPrb/gsoUGJRLmLfQ==,type:str]
    #ENC[AES256_GCM,data:XPLz7V1yryFO472Ihobx+y0lxvhW1qA4C1pcMeUL2ZCip5WzhPMjmFB1K9n7sG7NcJ3oMUQsSw==,iv:yUJ2lUhTzjcVr1YfqC3zFsZzLMKpuiTiaYxgRrQ31Ys=,tag:S0/b5e/2FJME9JcjuiEkfA==,type:comment]
    #ENC[AES256_GCM,data:ehaAN8+afG3JbOPuXF270/akeR72Wb1T5vTkI16nMrTHFrACkBtUb0P25GQu9cPo+R2cYDoiR1Sk8Q==,iv:ppqWpT3q/K8PGP1Y03nLkmOvvJjrP5pI/Z0ifIkM6Bs=,tag:jxE6Ap1gf8PJwbCybbwQgQ==,type:comment]
    #ENC[AES256_GCM,data:J5TZp5U/IH9oYJrEm+/6mdB8OG6dnbPAJ4kFu0HAeBuZTPBE,iv:i8GhkWiaF2i37VlZJpDx5ualCMzHrkRiLU3bFt4gHXE=,tag:xXZLk3JZ3cBQcdZmvrOyVQ==,type:comment]
    #ENC[AES256_GCM,data:JzbMnGX2S8NuisF/lPhO6rmHEtZvGRYzGDovbFX9,iv:fp11VoeeBrXt4gH5QCei20NaiWjeqby2SY+o/guW8YU=,tag:fskkZEwrIeeoA4SFbKnCvQ==,type:comment]
    S3_REGION: ENC[AES256_GCM,data:AMxMK0c=,iv:XthIx5wZ4ZA+0Y6pyP0P9SnH/ctxwamEcGZ60OVfrek=,tag:sMAUHYhZDltEirZFIBEt+A==,type:str]
    #ENC[AES256_GCM,data:nwNETp0bVuvJ5IvNsURQSWjGx7rbvg==,iv:DsEO3IRCKSj1QTsUR/A72qe4oSG7EPBQyiySwlY6Sik=,tag:li+z9EFq0DwZpy34JOOcaw==,type:comment]
    S3_ENDPOINT: ENC[AES256_GCM,data:gy481z4NQypXdXFeVxmLnwCy0gOjDw==,iv:jJh+BExtMcnMpc4w4Fv4XPnL1auCkmd5RFZeT7qCJRk=,tag:FQ9dKYIcE0RM3Mu4KO+d8w==,type:str]
    #ENC[AES256_GCM,data:FjPjjjBZCyelWYWXlZysr8lcCKFFm0RO,iv:wM4Fqz4oqCpgA+oYjo4GRvY8NqnxHaVyudtuHFGJQoE=,tag:e6IZcCBqdS6+vOB+rA8kfw==,type:comment]
    S3_BUCKET: ENC[AES256_GCM,data:GS7Bhki4uoY3OQHM,iv:0yIBwCKNVdukLiQ77xWnUVSPxaDox+a8CUjobziSeWE=,tag:Ow9nSDbNuMQEAa4YSKJ4Yg==,type:str]
    #ENC[AES256_GCM,data:2R348lQvT0yV9fNQE6RXcYTKgMY9,iv:AudaixUQgjHwne7ULeMe799ZdS0GPQE3WkBd8CgeGdU=,tag:I4b73XkSQl1tyBJiBNft0w==,type:comment]
    S3_PATH: ENC[AES256_GCM,data:mkmhPsLgeXN7JA036Q==,iv:9aqIHY5pNAJlmG5cj+noOUm+dpnlgjo6ukTWXxfPtNc=,tag:eYLb2o6bhAcsvScTPzHIFA==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaFpKaU5rL2lsYXcxSEY4
            c0xwZHY1czZMcWRIV01Hb24xMkxGdWxaSkdRCkxvUklJWjBmMlI3bkFBVXBlWFNO
            K25PNzJ3SkpQcGFYT25FYlRWcEs5bEEKLS0tIDdEcGJpVWt5UzlBU2NGcUZ5S1h2
            K21aa0NPYW5KZnhlbCt2R3RBZ29kM1UK+htKyw5AsHDQpsb/dA12dS2+qOXoQ8Vz
            zOIV5JZPPyrpG/5o1SYC4hYgdrsaFrfHcAPB6/cJsEvD0/wMxGZakw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T01:36:47Z"
    mac: ENC[AES256_GCM,data:fBFOP631kBKMA2iMt+E74bFu1+455FK+XR4gm/1mwU0jUQsD2Es0y/hx2wF1AHBAAn1uFAZn98/k76qscFOwSM5k24h9P48Hm1Z8vz1zTQGbbW48wkvimRN7se9vd3k/s9XaPFdQXVy4xHzfd539Yax4ShqiCbtk4/3y4UJyNHk=,iv:QiJI+YRLuU8zAbxOPFzc9sNeqgmP49upwskC4e5spNA=,tag:OK1h0pYkcoLaKzwFfJdo+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
