apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
type: Opaque
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:WLZOhP+PdN0fHr5PEmFkgdF5QjmlRkkbH7k=,iv:zI3Kll1Y7qYoK7Y/Y5dSc130IlloiLH5KWIhOxTYm6E=,tag:ZXw5FsupJJYv68VhIruRog==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7mCQra0vYNfVX1DajrvbxsndBBX047MNha9Tdy46Y3KqEjoStao1i0t4WFvUVBzMWH1BFdGvYIjr4bRtiDBhCQ==,iv:mVtFm1GXEX1ozgCLcR8FI+zSzab7uYidL4Yk3q+llYk=,tag:ZYv4OGmIFXLMF8MSmYhGaA==,type:str]
    S3_REGION: ENC[AES256_GCM,data:uFctVhc=,iv:35EPmix50YNZF2lqrL7yA1jcWeAej6RJ9nsPx8//qGQ=,tag:+yeXj1jdtDRiqnIELfT5Hw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:Eny6Sk/bm5gS/opPl9p44EmYdcvYNw==,iv:/O/87vYHrrJ0H0HqtPcTVRnktVy/wCF/41KBArJkddk=,tag:BpvK7+bl4sAKFLI0B6oJ+Q==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:vY2J6GtIF5hr1NpsEW82IXZlpA==,iv:UKEWYPaj3/1ey/j6GfaBUujNHzpuLIrJpIB0NPlnBBI=,tag:V5B5MRZ4XzLUbMWmMwVzAw==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTExKWis5UkVTMXJwdHNL
            L1kxTi9aVUg3ZVhVS0VzQ3ZkME82R0U0WUJrCiswSGRNZEdWVWlSc0lYZ0pkZHRN
            Vm9uRkpzZDR1MStKWWNPYXQrQmtETnMKLS0tIHk3eXhWdE44SjNEMGVtVGdSTm1O
            cnBOc2ZNN3M3K0JKVitub2lBMjI3NVUKL9EZOxOk7Njhz+7++BbQecZqMZvShK9a
            ROdpDxm1AbeRwejy5ZgSlje5mWh4XT4541LRgEmGx2Neqeq0kaanRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T05:47:34Z"
    mac: ENC[AES256_GCM,data:ENuENmIAYZdnd9+Dbl2YaW9sTTjtf+zShZiNu0pRBTg8hnynBCvbHoafD6JTWZzc6Bi12We5Fobk4puNRFYtBt15aNLczCYBiUYk2IvCTmcDQT9bbGB2Nu9s85KEiVMLcm/pbTtBBlVaLZKA1GU0C0F6UZinFPesLuWXPmiwqY8=,iv:mUqg5V4/7pUBKSOhW+97Z3H3L4c0wm6ZiO30N6Gc4jc=,tag:5eW8D9j5PFsInpuPyT8sSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
