---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  APP_BASE_URL: "https://backstage.webgrip.dev"
  APP_BACKEND_URL: ""
  APP_HOST: "0.0.0.0"
  APP_PORT: "7007"
  ORG_NAME: "WebGrip"
  AUTH_GITHUB_ENTERPRISE_INSTANCE_URL: "https://github.com"
  K8S_CLUSTER: "https://kubernetes.default.svc"
  K8S_CONFIG_CA_DATA: |-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lR
    TXpGUjhKRElSdkg5dEU0WnRHcVpkakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZ
    RFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEl3T0RBNU1qa3hORm9YRFRN
    MU1USXdOakE1TWpreApORm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6
    QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCQk9mMzdrbnZ3YStT
    cG55OTg1b2F1N1k0NzU5UnNtbnl6d2g0NForQTNZZmM3cW45Y3NnOXBEaWU0WUQK
    QTgreHFSZmN0N3VnQmJYM1FRRzJ3cVZyTmc2allUQmZNQTRHQTFVZER3RUIvd1FF
    QXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJ
    d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU0OHAwbTIvK2Fm
    QmZZcW9aNWpvM1FzT2hoT1l3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYjNTSkph
    VlAKSnpaa3JEQXhmbWFNOTI5dDRqa1pvMkhWNDh2ZURVVWU2UTBDSUJiTmNNSnQx
    b21JT3hqWlJ4RjBzTjJRY0EyUQpwdm9ROVQ4QUY3cGl2V0x1Ci0tLS0tRU5EIENF
    UlRJRklDQVRFLS0tLS0K
