---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  APP_BASE_URL: "https://backstage.webgrip.dev"
  APP_BACKEND_URL: ""
  APP_HOST: "0.0.0.0"
  APP_PORT: "7007"
  ORG_NAME: "WebGrip"
  AUTH_GITHUB_ENTERPRISE_INSTANCE_URL: "https://github.com"
  K8S_CLUSTER: ""
