---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./secret.sops.yaml
  - ./postgres-secret.sops.yaml
  - ./kubernetes-serviceaccount.yaml
  - ./database
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./dashboards/apps-backstage.yaml
