---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./backstage-secrets.yaml
  - ./base
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
