apiVersion: v1
kind: Secret
metadata:
    name: backstage-db-secret
    namespace: backstage
type: kubernetes.io/basic-auth
stringData:
    #ENC[AES256_GCM,data:CgMT1anwUNlrys6ZvHo7Of086OxMmC7cP7TrLZdoLZ1uWvtaDHyCqqAnkFlgTYddS1HFSb/kcL2fPl5zt2awM5ZC,iv:wyIgoSroPj9kWAwq3loAzesowscA9qi88iN93p+tgf4=,tag:U5G2K7jwhDSCDhP8mofA1Q==,type:comment]
    username: ENC[AES256_GCM,data:qFTUbwbRV3Ad,iv:b+TSQLj+D2GrfJRa4r7V3pQ8vo3bx8+ycNvbXnAOi1c=,tag:HQnhN5O7uy47+GesipyMIQ==,type:str]
    password: ENC[AES256_GCM,data:v9qObhkdIYVFM+/rNmOq/jGm,iv:j4wtxVhve9oEdkOl4uoFazKl6bmBx4lHUNYVeRYNPgk=,tag:GYDSQzEiCew+SLBQXBgurg==,type:str]
sops:
    age:
        - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdHprblFZYi9lSlBqZkFJ
            ZmMvZUl6dUdKWWx6ZWZ1S3gvNkYxNDhIWVNnCnJqSXVwME52SVcva1pRckxNaHpv
            Y1BubW5GaUhld1ZVMFYrazMzYkZxWjQKLS0tIEtyd2ZydDd5bU9GQUw3ODd2a3NR
            M1FzWS9zMzlzSFNhZ0NxYmtvTnU2QncKeDoEuHq4HobJjTRGjM8W9y1QZ5VjA4Qm
            GI1WOSHNbVrNhRE7OrIYzHceHQIwiWYrhaTMjk51kBnMgnTVzcx81Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T19:59:57Z"
    mac: ENC[AES256_GCM,data:zSUvNjZqrQx+X2Is4OSQDsFUhQNK92NdcEWoNVsZlnDqpJeQyHwRAdpxdZSzynYxmogEmFQ/985i3+XOou7oQdAv3BcTKyHxBFR+opa5SWrkouvT5Qta0DObj0VY0nhIVwbHNZjoxHPgkx6sVDp8uiW0u9BmvCzOrqVVQ+Jg2l0=,iv:DH9MhBfSic+6UR1eyogmMzj+ZRlqwZld7I+9/TrQz4M=,tag:qvfo9/zWqsp5fckHu1wFRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
