apiVersion: v1
kind: Secret
metadata:
  name: backstage-db-secret
  namespace: backstage
type: kubernetes.io/basic-auth
stringData:
  #ENC[AES256_GCM,data:CgMT1anwUNlrys6ZvHo7Of086OxMmC7cP7TrLZdoLZ1uWvtaDHyCqqAnkFlgTYddS1HFSb/kcL2fPl5zt2awM5ZC,iv:wyIgoSroPj9kWAwq3loAzesowscA9qi88iN93p+tgf4=,tag:U5G2K7jwhDSCDhP8mofA1Q==,type:comment]
  username: ENC[AES256_GCM,data:qFTUbwbRV3Ad,iv:b+TSQLj+D2GrfJRa4r7V3pQ8vo3bx8+ycNvbXnAOi1c=,tag:HQnhN5O7uy47+GesipyMIQ==,type:str]
  password: ENC[AES256_GCM,data:v9qObhkdIYVFM+/rNmOq/jGm,iv:j4wtxVhve9oEdkOl4uoFazKl6bmBx4lHUNYVeRYNPgk=,tag:GYDSQzEiCew+SLBQXBgurg==,type:str]
sops:
  age:
    - recipient: age1wkk4mjs434f8e6z65vlmxlmfc4z6a9seekzwmm42c9tuxyfnp97s6vk25t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdHprblFZYi9lSlBqZkFJ
        ZmMvZUl6dUdKWWx6ZWZ1S3gvNkYxNDhIWVNnCnJqSXVwME52SVcva1pRckxNaHpv
        Y1BubW5GaUhld1ZVMFYrazMzYkZxWjQKLS0tIEtyd2ZydDd5bU9GQUw3ODd2a3NR
        M1FzWS9zMzlzSFNhZ0NxYmtvTnU2QncKeDoEuHq4HobJjTRGjM8W9y1QZ5VjA4Qm
        GI1WOSHNbVrNhRE7OrIYzHceHQIwiWYrhaTMjk51kBnMgnTVzcx81Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T02:35:16Z"
  mac: ENC[AES256_GCM,data:tZenadkmkSx3JhsFThtyfOEfRVKmyrfLNJmk3a3ZGiE2HhIw1OyioJqqJ8pnWZ1FAgWSx+PPPvPmbAASSFGZHMylFv2gvnAgWMwVLSRpq69CF5k+j4DS08Memyt4O1TJtzpTyq5cdVFH43IA97PW/DZEeaVCJnDHxjLsSpXnpEY=,iv:abOMh6f8Ca1/hytq1xDPG+PaTBQZujILSstYO0RsSr8=,tag:OkLoMjeanE9OhFoEF5pG5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
