---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: backstage-db-password
  namespace: backstage
spec:
  length: 32
  digits: 10
  symbols: 5
  symbolCharacters: "!@#$%^&*()_+-="
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-db-secret
  namespace: backstage
spec:
  refreshInterval: 24h
  target:
    name: backstage-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: backstage
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: backstage-db-password
