---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: backstage-db-credentials-to-vault
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: backstage-db-secret
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: ${VAULT_ORG}/${VAULT_ENV}/clusters/${VAULT_CLUSTER}/apps/backstage/db
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: ${VAULT_ORG}/${VAULT_ENV}/clusters/${VAULT_CLUSTER}/apps/backstage/db
          property: password
